[workspace]
members = [
    "ota/cli",
    "registry/cli",
    "registry/core",
    "fake-cloud/server",
    "crates/raios-core",
    "crates/raios-dns-parse",
    "crates/raios-x509-time",
    "crates/raios-x509-spki",
    "crates/raios-http-parse",
    "crates/raios-lang",
    "crates/raios-w7-acquire-logic",
    "crates/raios-wasm-ir",
    "tools/descriptor-resign",
    "tools/core-policy-sign",
    "seed-kernel",
    "wasm-guests/svc-demo-echo",
    "wasm-guests/svc-demo-bufecho",
    "wasm-guests/svc-demo-certwindow",
    "wasm-guests/svc-demo-httphead",
    "wasm-guests/svc-demo-certspki",
    "wasm-guests/svc-demo-dnsparse",
    "wasm-guests/svc-build-assembler",
    "wasm-guests/svc-net-acquire-w7",
    "wasm-guests/svc-personal-shell-proof"
]
resolver = "2"

[patch.crates-io]
autocfg = { path = "vendor/autocfg-1.5.1" }
downcast-rs = { path = "vendor/downcast-rs-1.2.1" }
embedded-tls = { path = "vendor/embedded-tls-0.17.0" }
indexmap-nostd = { path = "vendor/indexmap-nostd-0.4.0" }
libm = { path = "vendor/libm-0.2.16" }
lock_api = { path = "vendor/lock_api-0.4.14" }
num-traits = { path = "vendor/num-traits-0.2.19" }
paste = { path = "vendor/paste-1.0.15" }
scopeguard = { path = "vendor/scopeguard-1.2.0" }
smallvec = { path = "vendor/smallvec-1.15.1" }
spin = { path = "vendor/spin-0.9.8" }
wasmi = { path = "vendor/wasmi-0.31.2" }
wasmi_arena = { path = "vendor/wasmi_arena-0.4.1" }
wasmi_core = { path = "vendor/wasmi_core-0.13.0" }
wasmparser-nostd = { path = "vendor/wasmparser-nostd-0.100.1" }
