use crate::agent_protocol_recovery_lifeline_protocol_types::RecoveryLifelineCommandVocabularyCandidate;

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLoaderRuntimeIsolationCandidate {
    pub(crate) command_candidate: RecoveryLifelineCommandVocabularyCandidate,
    pub(crate) command_vocabulary_available: bool,
    pub(crate) command_vocabulary_current_boot: bool,
    pub(crate) command_vocabulary_schema_ok: bool,
    pub(crate) command_vocabulary_binding_ok: bool,
    pub(crate) command_vocabulary_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) loader_address_space_boundary_present: bool,
    pub(crate) loader_entrypoint_abi_present: bool,
    pub(crate) loader_memory_map_constraints_present: bool,
    pub(crate) loader_capability_import_table_present: bool,
    pub(crate) loader_artifact_hash_binding_present: bool,
    pub(crate) loader_provider_separation_present: bool,
    pub(crate) loader_normal_module_separation_present: bool,
    pub(crate) rollback_transaction_engine_present: bool,
    pub(crate) durable_audit_rollback_persistence_present: bool,
    pub(crate) recovery_memory_provenance_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLoaderRuntimeIsolationCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) request_chain_valid: bool,
    pub(crate) command_vocabulary_envelope_exposed: bool,
    pub(crate) command_vocabulary_accepted: bool,
    pub(crate) isolation_requirements_exposed: bool,
    pub(crate) loader_runtime_isolation_ready: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryLoaderRuntimeIsolationSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryRollbackTransactionEngineCandidate {
    pub(crate) loader_candidate: RecoveryLoaderRuntimeIsolationCandidate,
    pub(crate) loader_runtime_isolation_available: bool,
    pub(crate) loader_runtime_isolation_current_boot: bool,
    pub(crate) loader_runtime_isolation_schema_ok: bool,
    pub(crate) loader_runtime_isolation_binding_ok: bool,
    pub(crate) loader_runtime_isolation_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) rollback_target_selection_present: bool,
    pub(crate) rollback_transaction_id_provenance_present: bool,
    pub(crate) rollback_last_good_binding_present: bool,
    pub(crate) rollback_disabled_module_set_binding_present: bool,
    pub(crate) rollback_artifact_hash_binding_present: bool,
    pub(crate) rollback_replay_preconditions_present: bool,
    pub(crate) rollback_recovery_capability_import_present: bool,
    pub(crate) rollback_atomic_apply_abort_semantics_present: bool,
    pub(crate) durable_audit_rollback_persistence_present: bool,
    pub(crate) recovery_memory_provenance_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryRollbackTransactionEngineCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) request_chain_valid: bool,
    pub(crate) command_vocabulary_envelope_exposed: bool,
    pub(crate) command_vocabulary_accepted: bool,
    pub(crate) loader_runtime_isolation_boundary_exposed: bool,
    pub(crate) loader_runtime_isolation_accepted: bool,
    pub(crate) transaction_requirements_exposed: bool,
    pub(crate) rollback_transaction_engine_ready: bool,
    pub(crate) rollback_preview_enabled: bool,
    pub(crate) rollback_apply_enabled: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryRollbackTransactionEngineSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryDurableAuditRollbackPersistenceCandidate {
    pub(crate) transaction_candidate: RecoveryRollbackTransactionEngineCandidate,
    pub(crate) rollback_transaction_engine_available: bool,
    pub(crate) rollback_transaction_engine_current_boot: bool,
    pub(crate) rollback_transaction_engine_schema_ok: bool,
    pub(crate) rollback_transaction_engine_binding_ok: bool,
    pub(crate) rollback_transaction_engine_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) persistence_device_inventory_present: bool,
    pub(crate) storage_layout_identity_present: bool,
    pub(crate) audit_append_log_identity_present: bool,
    pub(crate) rollback_store_identity_present: bool,
    pub(crate) transaction_replay_cursor_present: bool,
    pub(crate) last_good_checkpoint_binding_present: bool,
    pub(crate) write_ordering_present: bool,
    pub(crate) crash_consistency_present: bool,
    pub(crate) integrity_root_hash_chain_present: bool,
    pub(crate) recovery_memory_provenance_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryDurableAuditRollbackPersistenceCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) request_chain_valid: bool,
    pub(crate) command_vocabulary_envelope_exposed: bool,
    pub(crate) command_vocabulary_accepted: bool,
    pub(crate) loader_runtime_isolation_boundary_exposed: bool,
    pub(crate) loader_runtime_isolation_accepted: bool,
    pub(crate) rollback_transaction_engine_boundary_exposed: bool,
    pub(crate) rollback_transaction_engine_accepted: bool,
    pub(crate) persistence_requirements_exposed: bool,
    pub(crate) durable_audit_rollback_persistence_ready: bool,
    pub(crate) durable_writes_enabled: bool,
    pub(crate) rollback_replay_enabled: bool,
    pub(crate) recovery_memory_writes_enabled: bool,
    pub(crate) rollback_preview_enabled: bool,
    pub(crate) rollback_apply_enabled: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryDurableAuditRollbackPersistenceSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryMemoryProvenanceCandidate {
    pub(crate) persistence_candidate: RecoveryDurableAuditRollbackPersistenceCandidate,
    pub(crate) durable_audit_rollback_persistence_available: bool,
    pub(crate) durable_audit_rollback_persistence_current_boot: bool,
    pub(crate) durable_audit_rollback_persistence_schema_ok: bool,
    pub(crate) durable_audit_rollback_persistence_binding_ok: bool,
    pub(crate) durable_audit_rollback_persistence_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) source_record_ids_present: bool,
    pub(crate) source_schema_hashes_present: bool,
    pub(crate) memory_classification_present: bool,
    pub(crate) memory_authority_level_present: bool,
    pub(crate) memory_rollback_transaction_binding_present: bool,
    pub(crate) memory_last_good_checkpoint_binding_present: bool,
    pub(crate) recovery_only_export_profile_present: bool,
    pub(crate) memory_redaction_state_present: bool,
    pub(crate) memory_replay_window_present: bool,
    pub(crate) memory_audit_linkage_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryMemoryProvenanceCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) request_chain_valid: bool,
    pub(crate) command_vocabulary_envelope_exposed: bool,
    pub(crate) command_vocabulary_accepted: bool,
    pub(crate) loader_runtime_isolation_boundary_exposed: bool,
    pub(crate) loader_runtime_isolation_accepted: bool,
    pub(crate) rollback_transaction_engine_boundary_exposed: bool,
    pub(crate) rollback_transaction_engine_accepted: bool,
    pub(crate) durable_audit_rollback_persistence_boundary_exposed: bool,
    pub(crate) durable_audit_rollback_persistence_accepted: bool,
    pub(crate) memory_provenance_requirements_exposed: bool,
    pub(crate) recovery_memory_provenance_ready: bool,
    pub(crate) memory_writes_enabled: bool,
    pub(crate) provider_export_enabled: bool,
    pub(crate) durable_writes_enabled: bool,
    pub(crate) rollback_replay_enabled: bool,
    pub(crate) recovery_memory_writes_enabled: bool,
    pub(crate) rollback_preview_enabled: bool,
    pub(crate) rollback_apply_enabled: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryMemoryProvenanceSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandAdmissionCandidate {
    pub(crate) memory_candidate: RecoveryMemoryProvenanceCandidate,
    pub(crate) recovery_memory_provenance_available: bool,
    pub(crate) recovery_memory_provenance_current_boot: bool,
    pub(crate) recovery_memory_provenance_schema_ok: bool,
    pub(crate) recovery_memory_provenance_binding_ok: bool,
    pub(crate) recovery_memory_provenance_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) lifeline_status_admission_present: bool,
    pub(crate) rollback_preview_admission_present: bool,
    pub(crate) rollback_apply_admission_present: bool,
    pub(crate) disable_module_admission_present: bool,
    pub(crate) restart_last_good_admission_present: bool,
    pub(crate) load_recovery_artifact_by_hash_admission_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandAdmissionCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) memory_check: RecoveryMemoryProvenanceCheck,
    pub(crate) recovery_memory_provenance_boundary_exposed: bool,
    pub(crate) recovery_memory_provenance_accepted: bool,
    pub(crate) command_admission_requirements_exposed: bool,
    pub(crate) command_admission_ready: bool,
    pub(crate) lifeline_status_admission_present: bool,
    pub(crate) rollback_preview_admission_present: bool,
    pub(crate) rollback_apply_admission_present: bool,
    pub(crate) disable_module_admission_present: bool,
    pub(crate) restart_last_good_admission_present: bool,
    pub(crate) load_recovery_artifact_by_hash_admission_present: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryLifelineCommandAdmissionSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}
