use crate::{
    agent_protocol_recovery_lifeline::RecoveryLifelineCommandSpec,
    agent_protocol_recovery_runtime_types::{
        RecoveryLifelineCommandAdmissionCandidate, RecoveryLifelineCommandAdmissionCheck,
    },
    event_log,
};

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandEnvelopeReferenceInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) retained_lifeline_request_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) required_capability: Option<&'a str>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_admission_boundary_id: Option<&'a str>,
    pub(crate) lifeline_request_reference_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandEnvelopeReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) expected_command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) retained_lifeline_request_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) required_capability: Option<&'a str>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_admission_boundary_id: Option<&'a str>,
    pub(crate) lifeline_request_reference_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandEnvelopeCandidate {
    pub(crate) admission_candidate: RecoveryLifelineCommandAdmissionCandidate,
    pub(crate) command_admission_available: bool,
    pub(crate) command_admission_current_boot: bool,
    pub(crate) command_admission_schema_ok: bool,
    pub(crate) command_admission_binding_ok: bool,
    pub(crate) command_admission_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) command_id_supported: bool,
    pub(crate) argument_schema_matches: bool,
    pub(crate) argument_hash_present: bool,
    pub(crate) required_capability_matches: bool,
    pub(crate) target_locator_present: bool,
    pub(crate) reference_hash_matches: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandEnvelopeCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) admission_check: RecoveryLifelineCommandAdmissionCheck,
    pub(crate) command_admission_boundary_exposed: bool,
    pub(crate) command_admission_accepted: bool,
    pub(crate) command_envelope_reference_present: bool,
    pub(crate) command_id_supported: bool,
    pub(crate) argument_schema_matches: bool,
    pub(crate) argument_hash_present: bool,
    pub(crate) required_capability_matches: bool,
    pub(crate) target_locator_present: bool,
    pub(crate) reference_hash_matches: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryLifelineCommandEnvelopeSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) actual_admission_status: &'static str,
    pub(crate) actual_admission_reason: &'static str,
    pub(crate) command_admission_boundary_exposed: bool,
    pub(crate) command_admission_accepted: bool,
    pub(crate) command_envelope_reference_present: bool,
    pub(crate) command_id_supported: bool,
    pub(crate) argument_schema_matches: bool,
    pub(crate) argument_hash_present: bool,
    pub(crate) required_capability_matches: bool,
    pub(crate) target_locator_present: bool,
    pub(crate) reference_hash_matches: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandDispatchCandidate {
    pub(crate) envelope_candidate: RecoveryLifelineCommandEnvelopeCandidate,
    pub(crate) command_envelope_reference_available: bool,
    pub(crate) command_envelope_reference_current_boot: bool,
    pub(crate) command_envelope_reference_schema_ok: bool,
    pub(crate) command_envelope_reference_binding_ok: bool,
    pub(crate) command_envelope_reference_binding_reason: &'static str,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
    pub(crate) command_body_canonicalization_present: bool,
    pub(crate) command_handler_binding_present: bool,
    pub(crate) status_read_handler_present: bool,
    pub(crate) rollback_preview_authorization_present: bool,
    pub(crate) rollback_apply_authorization_present: bool,
    pub(crate) disable_module_target_binding_present: bool,
    pub(crate) restart_last_good_target_binding_present: bool,
    pub(crate) load_artifact_by_hash_target_binding_present: bool,
    pub(crate) recovery_memory_write_authority_present: bool,
    pub(crate) durable_audit_rollback_write_authority_present: bool,
    pub(crate) service_inventory_side_effect_boundary_present: bool,
    pub(crate) command_dispatch_behavior_present: bool,
    pub(crate) executor_capability_table_present: bool,
    pub(crate) side_effect_gate_present: bool,
    pub(crate) execution_enablement_present: bool,
    pub(crate) execution_preflight_present: bool,
    pub(crate) execution_intent_present: bool,
    pub(crate) execution_commit_gate_present: bool,
    pub(crate) execution_result_denial_present: bool,
    pub(crate) execution_audit_denial_present: bool,
    pub(crate) execution_observation_denial_present: bool,
    pub(crate) execution_completion_denial_present: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandDispatchCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) envelope_check: RecoveryLifelineCommandEnvelopeCheck,
    pub(crate) command_envelope_reference_available: bool,
    pub(crate) command_envelope_reference_accepted: bool,
    pub(crate) command_body_canonicalization_present: bool,
    pub(crate) command_handler_binding_present: bool,
    pub(crate) status_read_handler_present: bool,
    pub(crate) rollback_preview_authorization_present: bool,
    pub(crate) rollback_apply_authorization_present: bool,
    pub(crate) disable_module_target_binding_present: bool,
    pub(crate) restart_last_good_target_binding_present: bool,
    pub(crate) load_artifact_by_hash_target_binding_present: bool,
    pub(crate) recovery_memory_write_authority_present: bool,
    pub(crate) durable_audit_rollback_write_authority_present: bool,
    pub(crate) service_inventory_side_effect_boundary_present: bool,
    pub(crate) command_dispatch_behavior_present: bool,
    pub(crate) executor_capability_table_present: bool,
    pub(crate) side_effect_gate_present: bool,
    pub(crate) execution_enablement_present: bool,
    pub(crate) execution_preflight_present: bool,
    pub(crate) execution_intent_present: bool,
    pub(crate) execution_commit_gate_present: bool,
    pub(crate) execution_result_denial_present: bool,
    pub(crate) execution_audit_denial_present: bool,
    pub(crate) execution_observation_denial_present: bool,
    pub(crate) execution_completion_denial_present: bool,
    pub(crate) accepts_lifeline_command_body: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) rollback_preview_enabled: bool,
    pub(crate) rollback_apply_enabled: bool,
    pub(crate) recovery_memory_writes_enabled: bool,
    pub(crate) durable_writes_enabled: bool,
    pub(crate) rollback_replay_enabled: bool,
    pub(crate) provider_export_enabled: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryLifelineCommandDispatchSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) actual_envelope_status: &'static str,
    pub(crate) actual_envelope_reason: &'static str,
    pub(crate) command_envelope_reference_accepted: bool,
    pub(crate) command_body_canonicalization_present: bool,
    pub(crate) command_handler_binding_present: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) load_attempted: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandBodyCanonicalizationInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) retained_command_envelope_reference_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandBodyCanonicalizationReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) expected_command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) retained_command_envelope_reference_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandBodyCanonicalizationCandidate {
    pub(crate) dispatch_candidate: RecoveryLifelineCommandDispatchCandidate,
    pub(crate) command_body_reference_present: bool,
    pub(crate) command_body_reference_current_boot: bool,
    pub(crate) command_body_reference_schema_ok: bool,
    pub(crate) command_body_reference_binding_ok: bool,
    pub(crate) command_body_reference_binding_reason: &'static str,
    pub(crate) command_id_supported: bool,
    pub(crate) argument_schema_matches: bool,
    pub(crate) argument_hash_present: bool,
    pub(crate) target_locator_present: bool,
    pub(crate) command_envelope_reference_hash_matches: bool,
    pub(crate) command_dispatch_boundary_id_matches: bool,
    pub(crate) body_hash_matches: bool,
    pub(crate) direct_openai_recovery_shortcut_used: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandBodyCanonicalizationCheck {
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) dispatch_check: RecoveryLifelineCommandDispatchCheck,
    pub(crate) command_body_reference_present: bool,
    pub(crate) command_body_reference_accepted: bool,
    pub(crate) command_id_supported: bool,
    pub(crate) argument_schema_matches: bool,
    pub(crate) argument_hash_present: bool,
    pub(crate) target_locator_present: bool,
    pub(crate) command_envelope_reference_hash_matches: bool,
    pub(crate) command_dispatch_boundary_id_matches: bool,
    pub(crate) body_hash_matches: bool,
    pub(crate) accepts_raw_command_body: bool,
    pub(crate) accepts_lifeline_command_body: bool,
    pub(crate) accepts_lifeline_command_envelope: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) rollback_preview_enabled: bool,
    pub(crate) rollback_apply_enabled: bool,
    pub(crate) recovery_memory_writes_enabled: bool,
    pub(crate) durable_writes_enabled: bool,
    pub(crate) rollback_replay_enabled: bool,
    pub(crate) provider_export_enabled: bool,
    pub(crate) authorizes_recovery_load: bool,
    pub(crate) can_move_beyond_denial: bool,
    pub(crate) loads_recovery_loader: bool,
    pub(crate) loads_recovery_artifact: bool,
    pub(crate) creates_durable_records: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) allocates_service_slot: bool,
    pub(crate) service_inventory_change: &'static str,
    pub(crate) load_attempted: bool,
}

pub(crate) struct RecoveryLifelineCommandBodyCanonicalizationSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) actual_dispatch_status: &'static str,
    pub(crate) actual_dispatch_reason: &'static str,
    pub(crate) command_body_reference_accepted: bool,
    pub(crate) body_hash_matches: bool,
    pub(crate) dispatches_lifeline_command: bool,
    pub(crate) command_execution_enabled: bool,
    pub(crate) load_attempted: bool,
    pub(crate) passed: bool,
}
