use crate::{agent_protocol_recovery_lifeline::RecoveryLifelineCommandSpec, event_log};

#[derive(Clone, Copy)]
pub(crate) struct RecoveryMemoryWriteAuthorityInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) retained_load_artifact_by_hash_target_binding_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) recovery_memory_write_authority_id: Option<&'a str>,
    pub(crate) recovery_memory_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryMemoryWriteAuthorityReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) expected_recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) retained_load_artifact_by_hash_target_binding_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) recovery_memory_write_authority_id: Option<&'a str>,
    pub(crate) recovery_memory_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct RecoveryMemoryWriteAuthoritySelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct DurableAuditRollbackWriteAuthorityInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) retained_recovery_memory_write_authority_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) durable_audit_rollback_write_authority_id: Option<&'a str>,
    pub(crate) durable_audit_rollback_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct DurableAuditRollbackWriteAuthorityReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) expected_durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) retained_recovery_memory_write_authority_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) durable_audit_rollback_write_authority_id: Option<&'a str>,
    pub(crate) durable_audit_rollback_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct DurableAuditRollbackWriteAuthoritySelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryServiceInventorySideEffectBoundaryInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) retained_durable_audit_rollback_write_authority_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) service_inventory_side_effect_boundary_id: Option<&'a str>,
    pub(crate) service_inventory_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryServiceInventorySideEffectBoundaryReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) expected_service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) retained_durable_audit_rollback_write_authority_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) service_inventory_side_effect_boundary_id: Option<&'a str>,
    pub(crate) service_inventory_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct RecoveryServiceInventorySideEffectBoundarySelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandDispatchBehaviorInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) retained_service_inventory_side_effect_boundary_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) command_dispatch_behavior_id: Option<&'a str>,
    pub(crate) command_dispatch_behavior_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandDispatchBehaviorReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) expected_command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) retained_service_inventory_side_effect_boundary_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) command_dispatch_behavior_id: Option<&'a str>,
    pub(crate) command_dispatch_behavior_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct RecoveryLifelineCommandDispatchBehaviorSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandExecutorCapabilityTableInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) executor_capability_table_hash: Option<[u8; 32]>,
    pub(crate) retained_command_dispatch_behavior_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) executor_capability_table_id: Option<&'a str>,
    pub(crate) executor_capability_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandExecutorCapabilityTableReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) executor_capability_table_hash: Option<[u8; 32]>,
    pub(crate) expected_executor_capability_table_hash: Option<[u8; 32]>,
    pub(crate) retained_command_dispatch_behavior_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) executor_capability_table_id: Option<&'a str>,
    pub(crate) executor_capability_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct RecoveryLifelineCommandExecutorCapabilityTableSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandSideEffectGateInput<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) side_effect_gate_hash: Option<[u8; 32]>,
    pub(crate) retained_executor_capability_table_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) executor_capability_table_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) side_effect_gate_id: Option<&'a str>,
    pub(crate) side_effect_projection_hash: Option<[u8; 32]>,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryLifelineCommandSideEffectGateReferenceCheck<'a> {
    pub(crate) has_reference: bool,
    pub(crate) arity_valid: bool,
    pub(crate) scope: &'a str,
    pub(crate) side_effect_gate_hash: Option<[u8; 32]>,
    pub(crate) expected_side_effect_gate_hash: Option<[u8; 32]>,
    pub(crate) retained_executor_capability_table_event_id: Option<&'a str>,
    pub(crate) command_id: Option<&'a str>,
    pub(crate) argument_schema: Option<&'a str>,
    pub(crate) argument_hash: Option<[u8; 32]>,
    pub(crate) target_locator: Option<&'a str>,
    pub(crate) command_envelope_reference_hash: Option<[u8; 32]>,
    pub(crate) command_body_canonicalization_hash: Option<[u8; 32]>,
    pub(crate) handler_binding_hash: Option<[u8; 32]>,
    pub(crate) status_read_handler_hash: Option<[u8; 32]>,
    pub(crate) rollback_preview_authorization_hash: Option<[u8; 32]>,
    pub(crate) rollback_apply_authorization_hash: Option<[u8; 32]>,
    pub(crate) disable_module_target_binding_hash: Option<[u8; 32]>,
    pub(crate) restart_last_good_target_binding_hash: Option<[u8; 32]>,
    pub(crate) load_artifact_by_hash_target_binding_hash: Option<[u8; 32]>,
    pub(crate) recovery_memory_write_authority_hash: Option<[u8; 32]>,
    pub(crate) durable_audit_rollback_write_authority_hash: Option<[u8; 32]>,
    pub(crate) service_inventory_side_effect_boundary_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_behavior_hash: Option<[u8; 32]>,
    pub(crate) executor_capability_table_hash: Option<[u8; 32]>,
    pub(crate) command_dispatch_boundary_id: Option<&'a str>,
    pub(crate) side_effect_gate_id: Option<&'a str>,
    pub(crate) side_effect_projection_hash: Option<[u8; 32]>,
    pub(crate) normalized_spec: Option<RecoveryLifelineCommandSpec>,
    pub(crate) target_locator_value: Option<event_log::RecoveryCommandTargetLocator>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) valid: bool,
}

pub(crate) struct RecoveryLifelineCommandSideEffectGateSelfTestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_status: &'static str,
    pub(crate) expected_reason: &'static str,
    pub(crate) actual_status: &'static str,
    pub(crate) actual_reason: &'static str,
    pub(crate) passed: bool,
}
