pub(crate) const READ_EVIDENCE: &[&str] = &["computed_capability_grant"];
pub(crate) const DENIED_EVIDENCE: &[&str] = &["missing_required_evidence", "capability_denied"];
pub(crate) const PROVIDER_REQUEST_BINDING_DENIAL_EVIDENCE: &[&str] = &[
    "provider_request_binding_denied",
    "projected_packet_hash",
    "provider_write_not_attempted",
];
pub(crate) const PROVIDER_EXPORT_DENIAL_AUDIT_EVIDENCE: &[&str] = &[
    "provider_request_binding_denied",
    "projected_packet_hash",
    "exported_field_list_hash",
    "omitted_field_list_hash",
    "provider_write_not_attempted",
];
pub(crate) const PROVIDER_REQUEST_ENVELOPE_EVIDENCE: &[&str] = &[
    "provider_request_envelope_created",
    "request_body_hash",
    "envelope_hash",
    "provider_write_not_attempted",
];
pub(crate) const PROVIDER_REQUEST_BINDING_EVIDENCE: &[&str] = &[
    "provider_request_binding",
    "request_envelope_hash",
    "request_body_hash",
    "projected_packet_hash",
    "exported_field_list_hash",
    "omitted_field_list_hash",
    "positive_provider_trust",
    "provider_write_not_attempted",
];
pub(crate) const PROVIDER_EXPORT_AUDIT_BINDING_EVIDENCE: &[&str] = &[
    "provider_context_export_audit_binding",
    "provider_request_binding",
    "request_envelope_hash",
    "request_body_hash",
    "projected_packet_hash",
    "exported_field_list_hash",
    "omitted_field_list_hash",
    "positive_provider_trust",
    "context_injection_disabled",
];
pub(crate) const PROVIDER_BINDING_CONSUMPTION_EVIDENCE: &[&str] = &[
    "provider_binding_consumed_for_gate_evaluation",
    "provider_request_binding",
    "provider_context_export_audit_binding",
    "request_binding_hash",
    "export_audit_binding_hash",
    "provider_write_not_attempted",
    "context_injection_disabled",
];
pub(crate) const PROVIDER_CONTEXT_INJECTION_AUTHORIZATION_EVIDENCE: &[&str] = &[
    "provider_context_injection_authorization",
    "provider_binding_consumption",
    "request_binding_hash",
    "export_audit_binding_hash",
    "request_body_hash",
    "request_envelope_hash",
    "projected_packet_hash",
    "exported_field_list_hash",
    "omitted_field_list_hash",
    "positive_provider_trust",
    "provider_write_not_attempted",
    "context_injection_disabled",
];
pub(crate) const MODULE_LOAD_GATE_EVIDENCE: &[&str] = &[
    "missing_required_evidence",
    "capability_denied",
    "module_load_gate_evaluated",
    "module_manifest_reference_checked",
    "candidate_artifact_reference_checked",
    "vm_test_report_reference_checked",
    "local_attestation_reference_checked",
    "local_approval_reference_checked",
    "computed_capability_grant_reference_checked",
    "durable_audit_record_required",
    "rollback_plan_required",
    "rollback_bindings_required",
    "service_inventory_unchanged",
    "load_not_attempted",
];
pub(crate) const RECOVERY_ARTIFACT_LOAD_DENIAL_EVIDENCE: &[&str] = &[
    "missing_required_evidence",
    "capability_denied",
    "recovery_artifact_load_boundary_evaluated",
    "recovery_artifact_identity_required",
    "recovery_artifact_trust_required",
    "recovery_vm_test_required",
    "recovery_local_approval_required",
    "recovery_loader_required",
    "recovery_rollback_evidence_required",
    "normal_module_load_path_not_used",
    "load_not_attempted",
];
pub(crate) const MODULE_MANIFEST_REFERENCE_EVIDENCE: &[&str] = &[
    "module_manifest_reference",
    "manifest_reference_hash",
    "manifest_hash",
    "hash_reference_only",
    "manifest_json_not_accepted",
    "artifact_bytes_not_accepted",
    "load_not_attempted",
];
pub(crate) const MODULE_CANDIDATE_ARTIFACT_REFERENCE_EVIDENCE: &[&str] = &[
    "candidate_artifact_reference",
    "artifact_reference_hash",
    "manifest_reference_hash",
    "manifest_hash",
    "candidate_artifact_hash",
    "computed_capability_grant_hash",
    "hash_reference_only",
    "artifact_bytes_not_accepted",
    "load_not_attempted",
];
pub(crate) const MODULE_VM_TEST_REPORT_REFERENCE_EVIDENCE: &[&str] = &[
    "vm_test_report_reference",
    "vm_test_report_reference_hash",
    "vm_test_report_hash",
    "manifest_reference_hash",
    "artifact_reference_hash",
    "computed_capability_grant_hash",
    "hash_reference_only",
    "vm_report_json_not_accepted",
    "artifact_bytes_not_accepted",
    "load_not_attempted",
];
pub(crate) const MODULE_LOCAL_ATTESTATION_REFERENCE_EVIDENCE: &[&str] = &[
    "local_attestation_reference",
    "local_attestation_reference_hash",
    "local_attestation_hash",
    "manifest_reference_hash",
    "artifact_reference_hash",
    "vm_test_report_reference_hash",
    "computed_capability_grant_hash",
    "hash_reference_only",
    "local_attestation_json_not_accepted",
    "artifact_bytes_not_accepted",
    "load_not_attempted",
];
pub(crate) const MODULE_LOCAL_APPROVAL_REFERENCE_EVIDENCE: &[&str] = &[
    "local_approval_reference",
    "local_approval_reference_hash",
    "local_approval_hash",
    "local_attestation_reference_hash",
    "manifest_reference_hash",
    "artifact_reference_hash",
    "vm_test_report_reference_hash",
    "computed_capability_grant_hash",
    "hash_reference_only",
    "local_approval_text_not_accepted",
    "artifact_bytes_not_accepted",
    "load_not_attempted",
];
pub(crate) const MODULE_COMPUTED_GRANT_REFERENCE_EVIDENCE: &[&str] = &[
    "computed_capability_grant_reference",
    "computed_capability_grant_hash",
    "manifest_hash",
    "candidate_artifact_hash",
    "vm_test_report_hash",
    "local_attestation_hash",
    "hash_reference_only",
    "load_not_attempted",
];
pub(crate) const MODULE_AUDIT_ROLLBACK_REFERENCE_EVIDENCE: &[&str] = &[
    "audit_rollback_reference",
    "audit_record_hash",
    "rollback_plan_hash",
    "computed_capability_grant_hash",
    "retained_reference_event_id",
    "denial_event_id",
    "ram_only_service_slot_id",
    "hash_reference_only",
    "load_not_attempted",
];
pub(crate) const MODULE_SERVICE_SLOT_RESERVATION_EVIDENCE: &[&str] = &[
    "module_service_slot_reservation",
    "reservation_hash",
    "retained_reference_event_id",
    "retained_audit_rollback_reference_event_id",
    "computed_capability_grant_hash",
    "audit_record_hash",
    "rollback_plan_hash",
    "pre_load_service_inventory_hash",
    "ram_only_service_slot_id",
    "hash_reference_only",
    "load_not_attempted",
];
