    Send-AgentCommand -Command "agent module.audit_rollback_availability" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_availability"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_availability_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_availability.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "no_audit_records"; Needle = '"creates_durable_audit_records": false' },
        @{ Suffix = "no_rollback_plans"; Needle = '"creates_rollback_plans": false' },
        @{ Suffix = "no_rollback_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "ledger_schema"; Needle = '"schema": "raios.durable_audit_ledger.v0"' },
        @{ Suffix = "ledger_id"; Needle = '"id": "availability.durable_audit_ledger.current_boot"' },
        @{ Suffix = "ledger_reason"; Needle = '"reason": "durable_audit_ledger_missing"' },
        @{ Suffix = "ledger_present_false"; Needle = '"present": false' },
        @{ Suffix = "ledger_provenance_false"; Needle = '"provenance_valid": false' },
        @{ Suffix = "rollback_schema"; Needle = '"schema": "raios.rollback_store.v0"' },
        @{ Suffix = "rollback_id"; Needle = '"id": "availability.rollback_store.current_boot"' },
        @{ Suffix = "rollback_reason"; Needle = '"reason": "rollback_store_missing"' },
        @{ Suffix = "availability_status"; Needle = '"availability_status": "missing"' },
        @{ Suffix = "availability_reason"; Needle = '"availability_reason": "durable_audit_ledger_missing_and_rollback_store_missing"' },
        @{ Suffix = "audit_write_missing"; Needle = '"durable_audit_write_missing": true' },
        @{ Suffix = "rollback_install_missing"; Needle = '"rollback_install_missing": true' },
        @{ Suffix = "policy_missing"; Needle = '"durable_write_policy_available": false' },
        @{ Suffix = "rollback_policy_missing"; Needle = '"rollback_install_policy_available": false' },
        @{ Suffix = "not_durable_authority"; Needle = '"retained_hash_refs_are_durable_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_write_policy" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_write_policy"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_write_policy_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_write_policy.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "no_audit_records"; Needle = '"creates_durable_audit_records": false' },
        @{ Suffix = "no_rollback_plans"; Needle = '"creates_rollback_plans": false' },
        @{ Suffix = "no_rollback_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "durable_policy_schema"; Needle = '"schema": "raios.durable_audit_write_policy.v0"' },
        @{ Suffix = "durable_policy_id"; Needle = '"id": "policy.durable_audit_write.current_boot"' },
        @{ Suffix = "durable_policy_reason"; Needle = '"reason": "durable_write_policy_missing"' },
        @{ Suffix = "durable_policy_present_false"; Needle = '"present": false' },
        @{ Suffix = "durable_policy_binding_false"; Needle = '"binds_retained_evidence": false' },
        @{ Suffix = "durable_policy_availability_false"; Needle = '"binds_availability": false' },
        @{ Suffix = "rollback_policy_schema"; Needle = '"schema": "raios.rollback_install_policy.v0"' },
        @{ Suffix = "rollback_policy_id"; Needle = '"id": "policy.rollback_install.current_boot"' },
        @{ Suffix = "rollback_policy_reason"; Needle = '"reason": "rollback_install_policy_missing"' },
        @{ Suffix = "policy_status"; Needle = '"policy_status": "missing"' },
        @{ Suffix = "policy_reason"; Needle = '"policy_reason": "durable_write_policy_missing_and_rollback_install_policy_missing"' },
        @{ Suffix = "policy_missing"; Needle = '"durable_write_policy_missing": true' },
        @{ Suffix = "rollback_policy_missing"; Needle = '"rollback_install_policy_missing": true' },
        @{ Suffix = "policy_authority_false"; Needle = '"retained_hash_refs_are_policy_authority": false' },
        @{ Suffix = "availability_authority_false"; Needle = '"availability_facts_are_policy_authority": false' },
        @{ Suffix = "required_manifest"; Needle = '"module_manifest": "raios.module_manifest_reference.v0"' },
        @{ Suffix = "required_availability"; Needle = '"durable_audit_ledger": "raios.durable_audit_ledger.v0"' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_storage_layout" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_storage_layout"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_storage_layout_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_storage_layout.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "no_audit_records"; Needle = '"creates_durable_audit_records": false' },
        @{ Suffix = "no_rollback_plans"; Needle = '"creates_rollback_plans": false' },
        @{ Suffix = "device_schema"; Needle = '"schema": "raios.persistence_device_inventory.v0"' },
        @{ Suffix = "device_id"; Needle = '"id": "storage.persistence_device_inventory.current_boot"' },
        @{ Suffix = "device_reason"; Needle = '"reason": "persistence_device_inventory_missing"' },
        @{ Suffix = "device_present_false"; Needle = '"present": false' },
        @{ Suffix = "device_stable_false"; Needle = '"stable_identity": false' },
        @{ Suffix = "partition_inventory_false"; Needle = '"partition_inventory_available": false' },
        @{ Suffix = "write_path_false"; Needle = '"write_path_available": false' },
        @{ Suffix = "layout_schema"; Needle = '"schema": "raios.audit_rollback_storage_layout.v0"' },
        @{ Suffix = "layout_id"; Needle = '"id": "storage.audit_rollback_layout.current_boot"' },
        @{ Suffix = "layout_reason"; Needle = '"reason": "audit_rollback_storage_layout_missing"' },
        @{ Suffix = "layout_binding_false"; Needle = '"binds_persistence_device": false' },
        @{ Suffix = "audit_region_false"; Needle = '"has_audit_ledger_region": false' },
        @{ Suffix = "rollback_region_false"; Needle = '"has_rollback_store_region": false' },
        @{ Suffix = "append_slots_false"; Needle = '"append_slots_available": false' },
        @{ Suffix = "storage_status"; Needle = '"storage_layout_status": "missing"' },
        @{ Suffix = "storage_reason"; Needle = '"storage_layout_reason": "persistence_device_inventory_missing_and_storage_layout_missing"' },
        @{ Suffix = "storage_available_false"; Needle = '"storage_layout_available": false' },
        @{ Suffix = "storage_missing_true"; Needle = '"storage_layout_missing": true' },
        @{ Suffix = "append_engine_missing"; Needle = '"append_engine_missing": true' },
        @{ Suffix = "not_storage_authority"; Needle = '"retained_hash_refs_are_storage_authority": false' },
        @{ Suffix = "storage_not_append_authority"; Needle = '"storage_layout_facts_are_append_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_append_engine" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_append_engine"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_append_engine_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_append_engine.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "storage_inputs"; Needle = '"storage_layout_inputs": {' },
        @{ Suffix = "storage_available_false"; Needle = '"storage_layout_available": false' },
        @{ Suffix = "storage_missing_true"; Needle = '"storage_layout_missing": true' },
        @{ Suffix = "storage_not_engine_authority"; Needle = '"storage_layout_facts_are_append_engine_authority": false' },
        @{ Suffix = "audit_engine_schema"; Needle = '"schema": "raios.audit_ledger_append_engine.v0"' },
        @{ Suffix = "audit_engine_id"; Needle = '"id": "append_engine.audit_ledger.current_boot"' },
        @{ Suffix = "audit_engine_target"; Needle = '"target_schema": "raios.audit_record.v0"' },
        @{ Suffix = "audit_engine_reason"; Needle = '"reason": "audit_ledger_append_engine_missing"' },
        @{ Suffix = "audit_engine_present_false"; Needle = '"present": false' },
        @{ Suffix = "audit_engine_storage_binding_false"; Needle = '"binds_storage_layout": false' },
        @{ Suffix = "audit_engine_policy_binding_false"; Needle = '"binds_write_policy": false' },
        @{ Suffix = "audit_engine_append_only_false"; Needle = '"supports_append_only": false' },
        @{ Suffix = "rollback_engine_schema"; Needle = '"schema": "raios.rollback_store_transaction_engine.v0"' },
        @{ Suffix = "rollback_engine_id"; Needle = '"id": "append_engine.rollback_store.current_boot"' },
        @{ Suffix = "rollback_engine_target"; Needle = '"target_schema": "raios.rollback_plan.v0"' },
        @{ Suffix = "rollback_engine_reason"; Needle = '"reason": "rollback_store_transaction_engine_missing"' },
        @{ Suffix = "append_engine_status"; Needle = '"append_engine_status": "missing"' },
        @{ Suffix = "append_engine_reason"; Needle = '"append_engine_reason": "audit_ledger_append_engine_missing_and_rollback_store_transaction_engine_missing"' },
        @{ Suffix = "append_engine_available_false"; Needle = '"append_engine_available": false' },
        @{ Suffix = "append_engine_missing_true"; Needle = '"append_engine_missing": true' },
        @{ Suffix = "retained_not_engine_authority"; Needle = '"retained_hash_refs_are_append_engine_authority": false' },
        @{ Suffix = "engine_not_append_authority"; Needle = '"append_engine_facts_are_append_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_append_contract" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_append_contract"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_append_contract_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_append_contract.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "storage_inputs"; Needle = '"storage_layout_inputs": {' },
        @{ Suffix = "storage_input_device"; Needle = '"persistence_device_inventory": {' },
        @{ Suffix = "storage_input_layout"; Needle = '"audit_rollback_storage_layout": {' },
        @{ Suffix = "storage_input_available_false"; Needle = '"storage_layout_available": false' },
        @{ Suffix = "storage_input_authority_false"; Needle = '"storage_layout_facts_are_append_authority": false' },
        @{ Suffix = "append_engine_inputs"; Needle = '"append_engine_inputs": {' },
        @{ Suffix = "append_engine_input_audit"; Needle = '"audit_ledger_append_engine": {' },
        @{ Suffix = "append_engine_input_rollback"; Needle = '"rollback_store_transaction_engine": {' },
        @{ Suffix = "append_engine_input_available_false"; Needle = '"append_engine_available": false' },
        @{ Suffix = "append_engine_input_authority_false"; Needle = '"append_engine_facts_are_append_authority": false' },
        @{ Suffix = "audit_append_schema"; Needle = '"schema": "raios.audit_ledger_append_envelope.v0"' },
        @{ Suffix = "audit_append_id"; Needle = '"id": "append.audit_ledger.current_boot"' },
        @{ Suffix = "audit_append_target"; Needle = '"target_schema": "raios.audit_record.v0"' },
        @{ Suffix = "audit_append_storage_schema"; Needle = '"storage_layout_schema": "raios.audit_rollback_storage_layout.v0"' },
        @{ Suffix = "audit_append_storage_id"; Needle = '"storage_layout_id": "storage.audit_rollback_layout.current_boot"' },
        @{ Suffix = "audit_append_engine_id"; Needle = '"append_engine_id": "append_engine.audit_ledger.current_boot"' },
        @{ Suffix = "audit_append_policy_id"; Needle = '"write_policy_id": "policy.durable_audit_write.current_boot"' },
        @{ Suffix = "audit_append_availability_id"; Needle = '"availability_id": "availability.durable_audit_ledger.current_boot"' },
        @{ Suffix = "audit_append_provenance_schema"; Needle = '"append_contract_provenance_schema": "raios.append_contract_envelope_provenance.v0"' },
        @{ Suffix = "audit_append_reason"; Needle = '"reason": "audit_append_envelope_missing"' },
        @{ Suffix = "audit_append_storage_binding_false"; Needle = '"binds_storage_layout_id": false' },
        @{ Suffix = "audit_append_engine_binding_false"; Needle = '"binds_append_engine_id": false' },
        @{ Suffix = "audit_append_policy_id_binding_false"; Needle = '"binds_write_policy_id": false' },
        @{ Suffix = "audit_append_availability_id_binding_false"; Needle = '"binds_availability_id": false' },
        @{ Suffix = "audit_append_provenance_binding_false"; Needle = '"binds_envelope_provenance": false' },
        @{ Suffix = "storage_layout_false"; Needle = '"storage_layout_available": false' },
        @{ Suffix = "append_engine_false"; Needle = '"append_engine_available": false' },
        @{ Suffix = "rollback_transaction_schema"; Needle = '"schema": "raios.rollback_store_transaction_envelope.v0"' },
        @{ Suffix = "rollback_transaction_id"; Needle = '"id": "append.rollback_store.current_boot"' },
        @{ Suffix = "rollback_transaction_target"; Needle = '"target_schema": "raios.rollback_plan.v0"' },
        @{ Suffix = "rollback_transaction_engine_id"; Needle = '"append_engine_id": "append_engine.rollback_store.current_boot"' },
        @{ Suffix = "rollback_transaction_policy_id"; Needle = '"write_policy_id": "policy.rollback_install.current_boot"' },
        @{ Suffix = "rollback_transaction_availability_id"; Needle = '"availability_id": "availability.rollback_store.current_boot"' },
        @{ Suffix = "rollback_transaction_reason"; Needle = '"reason": "rollback_transaction_envelope_missing"' },
        @{ Suffix = "contract_status"; Needle = '"append_contract_status": "missing"' },
        @{ Suffix = "contract_reason"; Needle = '"append_contract_reason": "audit_append_envelope_missing_and_rollback_transaction_envelope_missing"' },
        @{ Suffix = "storage_layout_missing"; Needle = '"storage_layout_missing": true' },
        @{ Suffix = "append_engine_missing"; Needle = '"append_engine_missing": true' },
        @{ Suffix = "not_append_authority"; Needle = '"retained_hash_refs_are_append_authority": false' },
        @{ Suffix = "policy_not_append_authority"; Needle = '"policy_facts_are_append_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_append_payload_hash" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_append_payload_hash"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_append_payload_hash_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_append_payload_hash.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "retained_inputs"; Needle = '"retained_payload_inputs": {' },
        @{ Suffix = "audit_event"; Needle = '"audit_rollback": {"event_id": "event.current_boot.' },
        @{ Suffix = "service_slot_event"; Needle = '"service_slot_reservation": {"event_id": "event.current_boot.' },
        @{ Suffix = "audit_hash_input"; Needle = "`"audit_record_hash`": `"sha256:$moduleAuditHash`"" },
        @{ Suffix = "rollback_hash_input"; Needle = "`"rollback_plan_hash`": `"sha256:$moduleRollbackHash`"" },
        @{ Suffix = "inventory_hash_input"; Needle = "`"pre_load_service_inventory_hash`": `"sha256:$moduleAuditPreInventoryHash`"" },
        @{ Suffix = "reservation_hash_input"; Needle = "`"service_slot_reservation_hash`": `"sha256:$moduleServiceSlotReservationHash`"" },
        @{ Suffix = "slot_id_input"; Needle = "`"ram_only_service_slot_id`": `"$moduleAuditRamOnlyServiceSlotId`"" },
        @{ Suffix = "append_contract_inputs"; Needle = '"append_contract_inputs": {' },
        @{ Suffix = "contract_available_false"; Needle = '"append_contract_available": false' },
        @{ Suffix = "payload_facts"; Needle = '"append_payload_hash_facts": {' },
        @{ Suffix = "audit_payload_schema"; Needle = '"schema": "raios.audit_record_append_payload_hash_envelope.v0"' },
        @{ Suffix = "audit_payload_id"; Needle = '"id": "append_payload.audit_record.current_boot"' },
        @{ Suffix = "audit_payload_target"; Needle = '"target_schema": "raios.audit_record.v0"' },
        @{ Suffix = "audit_payload_contract"; Needle = '"append_contract_id": "append.audit_ledger.current_boot"' },
        @{ Suffix = "payload_hash_present"; Needle = '"payload_hash": "sha256:' },
        @{ Suffix = "audit_source_payload_hash"; Needle = "`"source_payload_hash`": `"sha256:$moduleAuditHash`"" },
        @{ Suffix = "audit_payload_reason"; Needle = '"reason": "audit_record_append_contract_missing"' },
        @{ Suffix = "binds_retained"; Needle = '"binds_retained_audit_rollback": true' },
        @{ Suffix = "binds_slot"; Needle = '"binds_service_slot_reservation": true' },
        @{ Suffix = "binds_request"; Needle = '"binds_pre_load_write_request": true' },
        @{ Suffix = "binds_contract_id"; Needle = '"binds_append_contract_id": true' },
        @{ Suffix = "binds_payload"; Needle = '"binds_payload_hash": true' },
        @{ Suffix = "retained_available"; Needle = '"retained_audit_rollback_available": true' },
        @{ Suffix = "service_slot_available"; Needle = '"service_slot_reservation_available": true' },
        @{ Suffix = "append_contract_available_false"; Needle = '"append_contract_available": false' },
        @{ Suffix = "rollback_payload_schema"; Needle = '"schema": "raios.rollback_transaction_append_payload_hash_envelope.v0"' },
        @{ Suffix = "rollback_payload_id"; Needle = '"id": "append_payload.rollback_transaction.current_boot"' },
        @{ Suffix = "rollback_payload_target"; Needle = '"target_schema": "raios.rollback_plan.v0"' },
        @{ Suffix = "rollback_source_payload_hash"; Needle = "`"source_payload_hash`": `"sha256:$moduleRollbackHash`"" },
        @{ Suffix = "rollback_payload_reason"; Needle = '"reason": "rollback_transaction_append_contract_missing"' },
        @{ Suffix = "payload_status"; Needle = '"payload_hash_status": "missing"' },
        @{ Suffix = "payload_reason"; Needle = '"payload_hash_reason": "audit_record_append_contract_missing"' },
        @{ Suffix = "retained_available_result"; Needle = '"retained_evidence_available": true' },
        @{ Suffix = "payload_available_false"; Needle = '"payload_hash_available": false' },
        @{ Suffix = "payload_missing_true"; Needle = '"payload_hash_missing": true' },
        @{ Suffix = "not_payload_authority"; Needle = '"payload_hash_envelopes_are_append_intent_authority": false' },
        @{ Suffix = "retained_not_payload_authority"; Needle = '"retained_hash_refs_are_payload_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_append_intent" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_append_intent"
    Assert-LogContainsFields -NamePrefix "protocol:module_audit_rollback_append_intent_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_append_intent.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "append_contract_inputs"; Needle = '"append_contract_inputs": {' },
        @{ Suffix = "audit_contract_input"; Needle = '"audit_append_envelope": {"schema": "raios.audit_ledger_append_envelope.v0", "status": "missing", "reason": "audit_append_envelope_missing"' },
        @{ Suffix = "rollback_contract_input"; Needle = '"rollback_transaction_envelope": {"schema": "raios.rollback_store_transaction_envelope.v0", "status": "missing", "reason": "rollback_transaction_envelope_missing"' },
        @{ Suffix = "contract_available_false"; Needle = '"append_contract_available": false' },
        @{ Suffix = "contract_not_intent_authority"; Needle = '"append_contract_facts_are_append_intent_authority": false' },
        @{ Suffix = "payload_inputs"; Needle = '"append_payload_hash_inputs": {' },
        @{ Suffix = "audit_payload_input"; Needle = '"audit_record_append_payload_hash": {"schema": "raios.audit_record_append_payload_hash_envelope.v0", "status": "missing", "reason": "audit_record_append_contract_missing"' },
        @{ Suffix = "rollback_payload_input"; Needle = '"rollback_transaction_append_payload_hash": {"schema": "raios.rollback_transaction_append_payload_hash_envelope.v0", "status": "missing", "reason": "rollback_transaction_append_contract_missing"' },
        @{ Suffix = "payload_hash_available_false"; Needle = '"payload_hash_available": false' },
        @{ Suffix = "payload_not_intent_authority"; Needle = '"payload_hash_envelopes_are_append_intent_authority": false' },
        @{ Suffix = "append_intent_facts"; Needle = '"append_intent_facts": {' },
        @{ Suffix = "audit_intent_schema"; Needle = '"schema": "raios.audit_record_append_intent.v0"' },
        @{ Suffix = "audit_intent_id"; Needle = '"id": "append_intent.audit_record.current_boot"' },
        @{ Suffix = "audit_intent_target"; Needle = '"target_schema": "raios.audit_record.v0"' },
        @{ Suffix = "audit_intent_contract_id"; Needle = '"append_contract_id": "append.audit_ledger.current_boot"' },
        @{ Suffix = "audit_intent_engine_id"; Needle = '"append_engine_id": "append_engine.audit_ledger.current_boot"' },
        @{ Suffix = "audit_intent_storage_id"; Needle = '"storage_layout_id": "storage.audit_rollback_layout.current_boot"' },
        @{ Suffix = "audit_intent_policy_id"; Needle = '"write_policy_id": "policy.durable_audit_write.current_boot"' },
        @{ Suffix = "audit_intent_availability_id"; Needle = '"availability_id": "availability.durable_audit_ledger.current_boot"' },
        @{ Suffix = "intent_provenance_schema"; Needle = '"intent_provenance_schema": "raios.append_intent_provenance.v0"' },
        @{ Suffix = "payload_hash_schema"; Needle = '"payload_hash_schema": "raios.append_intent_payload_hash.v0"' },
        @{ Suffix = "payload_hash_envelope_schema"; Needle = '"payload_hash_envelope_schema": "raios.append_payload_hash_envelope.canonical.v0"' },
        @{ Suffix = "audit_intent_reason"; Needle = '"reason": "audit_record_append_intent_missing"' },
        @{ Suffix = "audit_contract_binding_false"; Needle = '"binds_append_contract_id": false' },
        @{ Suffix = "audit_engine_binding_false"; Needle = '"binds_append_engine_id": false' },
        @{ Suffix = "audit_storage_binding_false"; Needle = '"binds_storage_layout_id": false' },
        @{ Suffix = "audit_policy_binding_false"; Needle = '"binds_write_policy_id": false' },
        @{ Suffix = "audit_availability_binding_false"; Needle = '"binds_availability_id": false' },
        @{ Suffix = "audit_payload_binding_false"; Needle = '"binds_payload_hash": false' },
        @{ Suffix = "audit_provenance_binding_false"; Needle = '"binds_intent_provenance": false' },
        @{ Suffix = "audit_payload_available_false"; Needle = '"payload_hash_available": false' },
        @{ Suffix = "rollback_intent_schema"; Needle = '"schema": "raios.rollback_transaction_append_intent.v0"' },
        @{ Suffix = "rollback_intent_id"; Needle = '"id": "append_intent.rollback_transaction.current_boot"' },
        @{ Suffix = "rollback_intent_target"; Needle = '"target_schema": "raios.rollback_plan.v0"' },
        @{ Suffix = "rollback_intent_contract_id"; Needle = '"append_contract_id": "append.rollback_store.current_boot"' },
        @{ Suffix = "rollback_intent_engine_id"; Needle = '"append_engine_id": "append_engine.rollback_store.current_boot"' },
        @{ Suffix = "rollback_intent_policy_id"; Needle = '"write_policy_id": "policy.rollback_install.current_boot"' },
        @{ Suffix = "rollback_intent_availability_id"; Needle = '"availability_id": "availability.rollback_store.current_boot"' },
        @{ Suffix = "rollback_intent_reason"; Needle = '"reason": "rollback_transaction_append_intent_missing"' },
        @{ Suffix = "intent_status"; Needle = '"append_intent_status": "missing"' },
        @{ Suffix = "intent_reason"; Needle = '"append_intent_reason": "audit_record_append_intent_missing_and_rollback_transaction_append_intent_missing"' },
        @{ Suffix = "intent_available_false"; Needle = '"append_intent_available": false' },
        @{ Suffix = "intent_missing_true"; Needle = '"append_intent_missing": true' },
        @{ Suffix = "payload_missing_true"; Needle = '"payload_hash_missing": true' },
        @{ Suffix = "intent_not_writer_authority"; Needle = '"append_intent_facts_are_writer_authority": false' },
        @{ Suffix = "retained_not_intent_authority"; Needle = '"retained_hash_refs_are_append_intent_authority": false' },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent module.audit_rollback_write_boundary" -ExpectedMarker "RAIOS_AGENT_END module.audit_rollback_write_boundary"
    Assert-LogContainsFields -NamePrefix "protocol:module_write_boundary_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.module_audit_rollback_write_boundary.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "writes_disabled"; Needle = '"writes_enabled": false' },
        @{ Suffix = "no_audit_records"; Needle = '"creates_durable_audit_records": false' },
        @{ Suffix = "no_rollback_plans"; Needle = '"creates_rollback_plans": false' },
        @{ Suffix = "no_rollback_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_recovery_artifact"; Needle = '"loads_recovery_artifact": false' },
        @{ Suffix = "request_schema"; Needle = '"schema": "raios.module_pre_load_audit_rollback_write_request.v0"' },
        @{ Suffix = "availability_inputs"; Needle = '"availability_inputs": {' },
        @{ Suffix = "ledger_availability_input"; Needle = '"durable_audit_ledger": {"schema": "raios.durable_audit_ledger.v0", "status": "missing", "reason": "durable_audit_ledger_missing"' },
        @{ Suffix = "rollback_availability_input"; Needle = '"rollback_store": {"schema": "raios.rollback_store.v0", "status": "missing", "reason": "rollback_store_missing"' },
        @{ Suffix = "policy_inputs"; Needle = '"policy_inputs": {' },
        @{ Suffix = "durable_policy_input"; Needle = '"durable_write_policy": {"schema": "raios.durable_audit_write_policy.v0", "status": "missing", "reason": "durable_write_policy_missing"' },
        @{ Suffix = "rollback_policy_input"; Needle = '"rollback_install_policy": {"schema": "raios.rollback_install_policy.v0", "status": "missing", "reason": "rollback_install_policy_missing"' },
        @{ Suffix = "append_contract_inputs"; Needle = '"append_contract_inputs": {' },
        @{ Suffix = "audit_append_input"; Needle = '"audit_append_envelope": {"schema": "raios.audit_ledger_append_envelope.v0", "status": "missing", "reason": "audit_append_envelope_missing"' },
        @{ Suffix = "rollback_transaction_input"; Needle = '"rollback_transaction_envelope": {"schema": "raios.rollback_store_transaction_envelope.v0", "status": "missing", "reason": "rollback_transaction_envelope_missing"' },
        @{ Suffix = "append_payload_hash_inputs"; Needle = '"append_payload_hash_inputs": {' },
        @{ Suffix = "audit_payload_hash_input"; Needle = '"audit_record_append_payload_hash": {"schema": "raios.audit_record_append_payload_hash_envelope.v0", "status": "missing", "reason": "audit_record_append_contract_missing"' },
        @{ Suffix = "rollback_payload_hash_input"; Needle = '"rollback_transaction_append_payload_hash": {"schema": "raios.rollback_transaction_append_payload_hash_envelope.v0", "status": "missing", "reason": "rollback_transaction_append_contract_missing"' },
        @{ Suffix = "append_payload_available_false"; Needle = '"payload_hash_available": false' },
        @{ Suffix = "append_payload_not_writer_authority"; Needle = '"payload_hash_envelopes_are_writer_authority": false' },
        @{ Suffix = "append_intent_inputs"; Needle = '"append_intent_inputs": {' },
        @{ Suffix = "audit_append_intent_input"; Needle = '"audit_record_append_intent": {"schema": "raios.audit_record_append_intent.v0", "status": "missing", "reason": "audit_record_append_intent_missing"' },
        @{ Suffix = "rollback_append_intent_input"; Needle = '"rollback_transaction_append_intent": {"schema": "raios.rollback_transaction_append_intent.v0", "status": "missing", "reason": "rollback_transaction_append_intent_missing"' },
        @{ Suffix = "append_intent_available_false"; Needle = '"append_intent_available": false' },
        @{ Suffix = "append_intent_not_writer_authority"; Needle = '"append_intent_facts_are_writer_authority": false' },
        @{ Suffix = "denial_schema"; Needle = '"schema": "raios.module_audit_rollback_write_denial_evidence.v0"' },
        @{ Suffix = "validation_status"; Needle = '"validation_status": "denied_missing_durable_write_boundary"' },
        @{ Suffix = "validation_reason"; Needle = '"validation_reason": "durable_audit_write_missing_and_rollback_install_missing"' },
        @{ Suffix = "audit_write_missing"; Needle = '"reason": "durable_audit_write_missing"' },
        @{ Suffix = "rollback_install_missing"; Needle = '"reason": "rollback_install_missing"' },
        @{ Suffix = "durable_policy_missing"; Needle = '"durable_write_policy_missing": true' },
        @{ Suffix = "rollback_policy_missing"; Needle = '"rollback_install_policy_missing": true' },
        @{ Suffix = "audit_append_missing"; Needle = '"audit_append_status": "missing"' },
        @{ Suffix = "rollback_transaction_missing"; Needle = '"rollback_transaction_status": "missing"' },
        @{ Suffix = "audit_payload_hash_missing"; Needle = '"audit_append_payload_hash_status": "missing"' },
        @{ Suffix = "rollback_payload_hash_missing"; Needle = '"rollback_transaction_append_payload_hash_status": "missing"' },
        @{ Suffix = "audit_append_intent_missing"; Needle = '"audit_append_intent_status": "missing"' },
        @{ Suffix = "rollback_transaction_intent_missing"; Needle = '"rollback_transaction_append_intent_status": "missing"' },
        @{ Suffix = "append_intent_missing"; Needle = '"append_intent_missing": true' },
        @{ Suffix = "payload_missing"; Needle = '"payload_hash_missing": true' },
        @{ Suffix = "storage_layout_missing"; Needle = '"storage_layout_missing": true' },
        @{ Suffix = "append_engine_missing"; Needle = '"append_engine_missing": true' },
        @{ Suffix = "not_append_authority"; Needle = '"retained_hash_refs_are_append_authority": false' },
        @{ Suffix = "not_payload_authority"; Needle = '"retained_hash_refs_are_payload_authority": false' },
        @{ Suffix = "not_append_intent_authority"; Needle = '"retained_hash_refs_are_append_intent_authority": false' },
        @{ Suffix = "not_durable_authority"; Needle = '"retained_hash_refs_are_durable_authority": false' },
        @{ Suffix = "manifest_event"; Needle = '"module_manifest": {"event_id": "event.current_boot.' },
        @{ Suffix = "artifact_event"; Needle = '"candidate_artifact": {"event_id": "event.current_boot.' },
        @{ Suffix = "vm_report_event"; Needle = '"vm_test_report": {"event_id": "event.current_boot.' },
        @{ Suffix = "grant_event"; Needle = '"computed_capability_grant": {"event_id": "event.current_boot.' },
        @{ Suffix = "attestation_event"; Needle = '"local_attestation": {"event_id": "event.current_boot.' },
        @{ Suffix = "approval_event"; Needle = '"local_approval": {"event_id": "event.current_boot.' },
        @{ Suffix = "audit_event"; Needle = '"audit_rollback": {"event_id": "event.current_boot.' },
        @{ Suffix = "service_slot_event"; Needle = '"service_slot_reservation": {"event_id": "event.current_boot.' },
        @{ Suffix = "manifest_hash"; Needle = "`"manifest_hash`": `"sha256:$moduleGrantManifestHash`"" },
        @{ Suffix = "artifact_hash"; Needle = "`"candidate_artifact_hash`": `"sha256:$moduleGrantArtifactHash`"" },
        @{ Suffix = "vm_report_hash"; Needle = "`"vm_test_report_hash`": `"sha256:$moduleGrantReportHash`"" },
        @{ Suffix = "attestation_hash"; Needle = "`"local_attestation_hash`": `"sha256:$moduleGrantAttestationHash`"" },
        @{ Suffix = "approval_hash"; Needle = "`"local_approval_hash`": `"sha256:$moduleAuditLocalApprovalHash`"" },
        @{ Suffix = "audit_hash"; Needle = "`"audit_record_hash`": `"sha256:$moduleAuditHash`"" },
        @{ Suffix = "rollback_hash"; Needle = "`"rollback_plan_hash`": `"sha256:$moduleRollbackHash`"" },
        @{ Suffix = "service_slot_hash"; Needle = "`"service_slot_reservation_hash`": `"sha256:$moduleServiceSlotReservationHash`"" },
        @{ Suffix = "slot_id"; Needle = "`"ram_only_service_slot_id`": `"$moduleAuditRamOnlyServiceSlotId`"" },
        @{ Suffix = "can_load_false"; Needle = '"can_load_now": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
