    Send-AgentCommand -Command "agent recovery.lifeline_request_diagnostic" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_request_diagnostic"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_request_diag_absent_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_request_diagnostic.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "status"; Needle = '"validation_status": "missing"' },
        @{ Suffix = "reason"; Needle = '"validation_reason": "recovery_lifeline_request_reference_absent"' },
        @{ Suffix = "retained_missing"; Needle = '"reason": "no_valid_recovery_lifeline_request_reference_retained"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    $recoveryLifelineRequestCanonical = @(
        "canonicalization=raios.recovery_lifeline_request.canonical.v0",
        "schema=raios.recovery_lifeline_request.v0",
        "requested_capability=cap.recovery.load_artifact",
        "load_mode=recovery_only",
        "subject=agent.session.serial",
        "resource=recovery_lifeline",
        "scope=current_boot",
        "retained_recovery_artifact_identity_event_id=$recoveryIdentityEventId",
        "retained_recovery_artifact_trust_event_id=$recoveryTrustEventId",
        "retained_recovery_artifact_vm_test_event_id=$recoveryVmTestEventId",
        "retained_recovery_artifact_local_approval_event_id=$recoveryLocalApprovalEventId",
        "retained_recovery_artifact_loader_event_id=$recoveryLoaderEventId",
        "retained_recovery_artifact_rollback_evidence_event_id=$recoveryRollbackEvidenceEventId",
        "identity_reference_sha256=$recoveryIdentityReferenceHash",
        "trust_reference_sha256=$recoveryTrustReferenceHash",
        "vm_test_reference_sha256=$recoveryVmTestReferenceHash",
        "local_approval_reference_sha256=$recoveryLocalApprovalReferenceHash",
        "loader_reference_sha256=$recoveryLoaderReferenceHash",
        "rollback_evidence_reference_sha256=$recoveryRollbackEvidenceReferenceHash",
        "artifact_sha256=$recoveryArtifactHash",
        "trust_sha256=$recoveryTrustHash",
        "vm_test_sha256=$recoveryVmTestHash",
        "local_approval_sha256=$recoveryLocalApprovalHash",
        "loader_sha256=$recoveryLoaderHash",
        "rollback_evidence_sha256=$recoveryRollbackEvidenceHash",
        "accepts_lifeline_request_json=false",
        "accepts_loader_descriptor=false",
        "accepts_artifact_bytes=false",
        "loads_recovery_loader=false",
        "loads_recovery_artifact=false",
        "authorizes_recovery_load=false",
        "creates_durable_records=false",
        "installs_rollback_plan=false",
        "allocates_service_slot=false",
        "service_inventory_change=none",
        "load_attempted=false"
    ) -join "`n"
    $recoveryLifelineRequestReferenceHash = Get-TextSha256 -Text $recoveryLifelineRequestCanonical
    $recoveryLifelineRequestCommand = "agent recovery.lifeline_request_diagnostic $recoveryLifelineRequestReferenceHash $recoveryIdentityEventId $recoveryTrustEventId $recoveryVmTestEventId $recoveryLocalApprovalEventId $recoveryLoaderEventId $recoveryRollbackEvidenceEventId $recoveryIdentityReferenceHash $recoveryTrustReferenceHash $recoveryVmTestReferenceHash $recoveryLocalApprovalReferenceHash $recoveryLoaderReferenceHash $recoveryRollbackEvidenceReferenceHash $recoveryArtifactHash $recoveryTrustHash $recoveryVmTestHash $recoveryLocalApprovalHash $recoveryLoaderHash $recoveryRollbackEvidenceHash"

    Send-AgentCommand -Command $recoveryLifelineRequestCommand -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_request_diagnostic"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_request_diag_valid_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "status"; Needle = '"validation_status": "valid_hash_reference_load_still_denied"' },
        @{ Suffix = "reason"; Needle = '"validation_reason": "recovery_lifeline_request_reference_valid_but_lifeline_protocol_missing"' },
        @{ Suffix = "retention_mutation"; Needle = '"global_event_log_mutation": "valid_hash_reference_retention_only"' },
        @{ Suffix = "retained_status"; Needle = '"status": "retained_hash_reference_load_still_denied"' },
        @{ Suffix = "retained_event_id"; Needle = '"event_id": "event.current_boot.' },
        @{ Suffix = "recorded_event_id"; Needle = '"recorded_event_id": "event.current_boot.' },
        @{ Suffix = "retained_matches"; Needle = '"matches_current_reference": true' },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_ref_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "rollback_ref_hash"; Needle = "`"rollback_evidence_reference_hash`": `"sha256:$recoveryRollbackEvidenceReferenceHash`"" },
        @{ Suffix = "rollback_hash"; Needle = "`"rollback_evidence_hash`": `"sha256:$recoveryRollbackEvidenceHash`"" },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "no_authority"; Needle = '"authorizes_recovery_load": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    $recoveryLifelineRequestResponse = Get-LastAgentResponseJson -Method "recovery.lifeline_request_diagnostic"
    $recoveryLifelineRequestEventId = [string]$recoveryLifelineRequestResponse.body.result.retained_recovery_lifeline_request_reference.event_id
    Assert-CurrentBootEventId -Name "protocol:recovery_lifeline_request_retained_reference_event_id_captured" -Value $recoveryLifelineRequestEventId

    Send-AgentCommand -Command "agent recovery.lifeline_request_diagnostic_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_request_diagnostic_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_request_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_request_diagnostic_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_request_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 11' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "absent_case"; Needle = '"case": "absent_reference"' },
        @{ Suffix = "valid_case"; Needle = '"case": "accepted_current_boot_lifeline_request_still_denied"' },
        @{ Suffix = "stale_case"; Needle = '"case": "stale_previous_boot_reference"' },
        @{ Suffix = "identity_not_current_case"; Needle = '"case": "retained_identity_event_not_current_boot"' },
        @{ Suffix = "rollback_not_current_case"; Needle = '"case": "retained_rollback_evidence_event_not_current_boot"' },
        @{ Suffix = "identity_missing_case"; Needle = '"case": "retained_identity_missing"' },
        @{ Suffix = "rollback_schema_case"; Needle = '"case": "retained_rollback_evidence_wrong_schema_or_variant"' },
        @{ Suffix = "substituted_case"; Needle = '"case": "substituted_rollback_evidence_reference_record"' },
        @{ Suffix = "request_mismatch_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "rollback_mismatch_case"; Needle = '"case": "rollback_evidence_reference_hash_mismatch"' },
        @{ Suffix = "chain_mismatch_case"; Needle = '"case": "retained_chain_mismatch"' },
        @{ Suffix = "valid_reason"; Needle = '"actual_reason": "recovery_lifeline_request_reference_valid_but_lifeline_protocol_missing"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.lifeline_protocol_diagnostic" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_protocol_diagnostic"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_protocol_diag_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_protocol_state.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_protocol_state_records": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "provider_shortcut_false"; Needle = '"provider_shortcut_used": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "can_report_gaps"; Needle = '"can_report_protocol_gaps": true' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "trust_event"; Needle = "`"retained_recovery_artifact_trust_event_id`": `"$recoveryTrustEventId`"" },
        @{ Suffix = "vm_event"; Needle = "`"retained_recovery_artifact_vm_test_event_id`": `"$recoveryVmTestEventId`"" },
        @{ Suffix = "approval_event"; Needle = "`"retained_recovery_artifact_local_approval_event_id`": `"$recoveryLocalApprovalEventId`"" },
        @{ Suffix = "loader_event"; Needle = "`"retained_recovery_artifact_loader_event_id`": `"$recoveryLoaderEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "protocol_state_missing"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "command_vocab_missing"; Needle = '"reason": "recovery_lifeline_command_vocabulary_missing"' },
        @{ Suffix = "isolation_missing"; Needle = '"reason": "recovery_loader_runtime_isolation_missing"' },
        @{ Suffix = "rollback_engine_missing"; Needle = '"reason": "recovery_rollback_transaction_engine_missing"' },
        @{ Suffix = "durable_missing"; Needle = '"reason": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_provenance_missing"; Needle = '"reason": "recovery_memory_provenance_missing"' },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "no_artifact_load"; Needle = '"loads_recovery_artifact": false' },
        @{ Suffix = "no_authority"; Needle = '"authorizes_recovery_load": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryLifelineProtocolResponse = Get-LastAgentResponseJson -Method "recovery.lifeline_protocol_diagnostic"
    $recoveryLifelineProtocolRequestEventId = [string]$recoveryLifelineProtocolResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryLifelineProtocolRequestMatches = $recoveryLifelineProtocolRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_lifeline_protocol_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryLifelineProtocolRequestMatches -Actual $recoveryLifelineProtocolRequestEventId
    if (-not $recoveryLifelineProtocolRequestMatches) {
        throw "Expected recovery lifeline protocol request event id $recoveryLifelineRequestEventId, got $recoveryLifelineProtocolRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.lifeline_protocol_diagnostic_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_protocol_diagnostic_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_protocol_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_protocol_state_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_protocol_state_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 15' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "stale_case"; Needle = '"case": "stale_dropped_lifeline_request_event_id"' },
        @{ Suffix = "previous_case"; Needle = '"case": "previous_boot_lifeline_request_event_id"' },
        @{ Suffix = "schema_case"; Needle = '"case": "wrong_schema_lifeline_request_event_id"' },
        @{ Suffix = "substituted_case"; Needle = '"case": "substituted_lifeline_request_record"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "identity_event_case"; Needle = '"case": "retained_identity_event_id_mismatch"' },
        @{ Suffix = "rollback_hash_case"; Needle = '"case": "rollback_evidence_reference_hash_mismatch"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "protocol_state_case"; Needle = '"case": "accepted_current_boot_request_protocol_state_missing"' },
        @{ Suffix = "command_vocab_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "isolation_case"; Needle = '"case": "loader_runtime_isolation_missing_after_command_vocabulary"' },
        @{ Suffix = "rollback_engine_case"; Needle = '"case": "rollback_transaction_engine_missing_after_isolation"' },
        @{ Suffix = "durable_case"; Needle = '"case": "durable_audit_rollback_persistence_missing_after_engine"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing_after_persistence"' },
        @{ Suffix = "valid_reason"; Needle = '"actual_reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.lifeline_command_vocabulary" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_command_vocabulary"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_command_vocab_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_command_vocabulary_records": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_exposed": true' },
        @{ Suffix = "commands_defined"; Needle = '"state": "defined_non_executable"' },
        @{ Suffix = "command_count"; Needle = '"command_count": 6' },
        @{ Suffix = "envelope_schema"; Needle = '"argument_envelope_schema": "raios.recovery_lifeline_command_envelope.v0"' },
        @{ Suffix = "status_command"; Needle = '"id": "recovery.lifeline.status"' },
        @{ Suffix = "rollback_preview_command"; Needle = '"id": "recovery.lifeline.rollback_preview"' },
        @{ Suffix = "rollback_apply_command"; Needle = '"id": "recovery.lifeline.rollback_apply"' },
        @{ Suffix = "disable_module_command"; Needle = '"id": "recovery.lifeline.disable_module"' },
        @{ Suffix = "restart_last_good_command"; Needle = '"id": "recovery.lifeline.restart_last_good"' },
        @{ Suffix = "load_artifact_command"; Needle = '"id": "recovery.lifeline.load_artifact_by_hash"' },
        @{ Suffix = "rollback_cap"; Needle = '"required_capability": "cap.recovery.rollback"' },
        @{ Suffix = "module_disable_cap"; Needle = '"required_capability": "cap.recovery.module.disable"' },
        @{ Suffix = "service_restart_cap"; Needle = '"required_capability": "cap.recovery.service.restart"' },
        @{ Suffix = "load_cap"; Needle = '"required_capability": "cap.recovery.load_artifact"' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "execution_false"; Needle = '"command_execution_enabled": false' },
        @{ Suffix = "dispatch_false"; Needle = '"dispatches_commands": false' },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "no_artifact_load"; Needle = '"loads_recovery_artifact": false' },
        @{ Suffix = "no_authority"; Needle = '"authorizes_recovery_load": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryLifelineCommandVocabularyResponse = Get-LastAgentResponseJson -Method "recovery.lifeline_command_vocabulary"
    $recoveryLifelineCommandVocabularyRequestEventId = [string]$recoveryLifelineCommandVocabularyResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryLifelineCommandVocabularyRequestMatches = $recoveryLifelineCommandVocabularyRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_lifeline_command_vocab_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryLifelineCommandVocabularyRequestMatches -Actual $recoveryLifelineCommandVocabularyRequestEventId
    if (-not $recoveryLifelineCommandVocabularyRequestMatches) {
        throw "Expected recovery lifeline command vocabulary request event id $recoveryLifelineRequestEventId, got $recoveryLifelineCommandVocabularyRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.lifeline_command_vocabulary_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_command_vocabulary_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_command_vocab_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_command_vocabulary_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 16' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "stale_request_case"; Needle = '"case": "stale_dropped_lifeline_request_event_id"' },
        @{ Suffix = "previous_request_case"; Needle = '"case": "previous_boot_lifeline_request_event_id"' },
        @{ Suffix = "wrong_request_schema_case"; Needle = '"case": "wrong_schema_lifeline_request_event_id"' },
        @{ Suffix = "substituted_request_case"; Needle = '"case": "substituted_lifeline_request_record"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "missing_protocol_state_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "previous_protocol_state_case"; Needle = '"case": "previous_boot_lifeline_protocol_state"' },
        @{ Suffix = "wrong_protocol_state_schema_case"; Needle = '"case": "wrong_schema_lifeline_protocol_state"' },
        @{ Suffix = "substituted_protocol_state_case"; Needle = '"case": "substituted_lifeline_protocol_state"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "isolation_missing_case"; Needle = '"case": "loader_runtime_isolation_missing"' },
        @{ Suffix = "rollback_engine_missing_case"; Needle = '"case": "rollback_transaction_engine_missing"' },
        @{ Suffix = "durable_missing_case"; Needle = '"case": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_commands_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "recovery_lifeline_command_behavior_not_implemented"' },
        @{ Suffix = "execution_false"; Needle = '"command_execution_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.loader_runtime_isolation" -ExpectedMarker "RAIOS_AGENT_END recovery.loader_runtime_isolation"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_loader_runtime_isolation_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_loader_runtime_isolation.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_loader_runtime_isolation_records": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_envelope_exposed": true' },
        @{ Suffix = "vocab_not_accepted"; Needle = '"command_vocabulary_accepted": false' },
        @{ Suffix = "requirements_exposed"; Needle = '"isolation_requirements_exposed": true' },
        @{ Suffix = "isolation_not_ready"; Needle = '"loader_runtime_isolation_ready": false' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "command_vocab_schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary.v0"' },
        @{ Suffix = "command_vocab_envelope"; Needle = '"state": "defined_read_only_envelope"' },
        @{ Suffix = "loader_boundary_schema"; Needle = '"loader_runtime_isolation_schema": "raios.recovery_loader_runtime_isolation.v0"' },
        @{ Suffix = "address_space_schema"; Needle = '"schema": "raios.recovery_loader_address_space_boundary.v0"' },
        @{ Suffix = "entrypoint_schema"; Needle = '"schema": "raios.recovery_loader_entrypoint_abi.v0"' },
        @{ Suffix = "memory_map_schema"; Needle = '"schema": "raios.recovery_loader_memory_map_constraints.v0"' },
        @{ Suffix = "import_table_schema"; Needle = '"schema": "raios.recovery_loader_capability_import_table.v0"' },
        @{ Suffix = "artifact_hash_schema"; Needle = '"schema": "raios.recovery_loader_artifact_hash_binding.v0"' },
        @{ Suffix = "provider_sep_schema"; Needle = '"schema": "raios.recovery_loader_provider_separation.v0"' },
        @{ Suffix = "normal_module_sep_schema"; Needle = '"schema": "raios.recovery_loader_normal_module_separation.v0"' },
        @{ Suffix = "address_space_missing"; Needle = '"reason": "recovery_loader_address_space_boundary_missing"' },
        @{ Suffix = "entrypoint_missing"; Needle = '"reason": "recovery_loader_entrypoint_abi_missing"' },
        @{ Suffix = "memory_map_missing"; Needle = '"reason": "recovery_loader_memory_map_constraints_missing"' },
        @{ Suffix = "import_table_missing"; Needle = '"reason": "recovery_loader_capability_import_table_missing"' },
        @{ Suffix = "artifact_hash_missing"; Needle = '"reason": "recovery_loader_artifact_hash_binding_missing"' },
        @{ Suffix = "provider_sep_missing"; Needle = '"reason": "recovery_loader_provider_separation_missing"' },
        @{ Suffix = "normal_module_sep_missing"; Needle = '"reason": "recovery_loader_normal_module_separation_missing"' },
        @{ Suffix = "rollback_engine_missing"; Needle = '"reason": "recovery_rollback_transaction_engine_missing"' },
        @{ Suffix = "durable_missing"; Needle = '"reason": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_provenance_missing"; Needle = '"reason": "recovery_memory_provenance_missing"' },
        @{ Suffix = "loader_execution_false"; Needle = '"loader_execution_enabled": false' },
        @{ Suffix = "dispatch_false"; Needle = '"recovery_lifeline_command_dispatch_enabled": false' },
        @{ Suffix = "normal_path_false"; Needle = '"normal_module_load_path_used": false' },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "no_artifact_load"; Needle = '"loads_recovery_artifact": false' },
        @{ Suffix = "no_authority"; Needle = '"authorizes_recovery_load": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryLoaderRuntimeIsolationResponse = Get-LastAgentResponseJson -Method "recovery.loader_runtime_isolation"
    $recoveryLoaderRuntimeIsolationRequestEventId = [string]$recoveryLoaderRuntimeIsolationResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryLoaderRuntimeIsolationRequestMatches = $recoveryLoaderRuntimeIsolationRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_loader_runtime_isolation_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryLoaderRuntimeIsolationRequestMatches -Actual $recoveryLoaderRuntimeIsolationRequestEventId
    if (-not $recoveryLoaderRuntimeIsolationRequestMatches) {
        throw "Expected recovery loader runtime isolation request event id $recoveryLifelineRequestEventId, got $recoveryLoaderRuntimeIsolationRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.loader_runtime_isolation_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.loader_runtime_isolation_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_loader_runtime_isolation_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_loader_runtime_isolation_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_loader_runtime_isolation_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 27' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "stale_request_case"; Needle = '"case": "stale_dropped_lifeline_request_event_id"' },
        @{ Suffix = "previous_request_case"; Needle = '"case": "previous_boot_lifeline_request_event_id"' },
        @{ Suffix = "wrong_request_schema_case"; Needle = '"case": "wrong_schema_lifeline_request_event_id"' },
        @{ Suffix = "substituted_request_case"; Needle = '"case": "substituted_lifeline_request_record"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "missing_protocol_state_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "previous_protocol_state_case"; Needle = '"case": "previous_boot_lifeline_protocol_state"' },
        @{ Suffix = "wrong_protocol_state_schema_case"; Needle = '"case": "wrong_schema_lifeline_protocol_state"' },
        @{ Suffix = "substituted_protocol_state_case"; Needle = '"case": "substituted_lifeline_protocol_state"' },
        @{ Suffix = "missing_command_vocab_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "previous_command_vocab_case"; Needle = '"case": "previous_boot_lifeline_command_vocabulary"' },
        @{ Suffix = "wrong_command_vocab_case"; Needle = '"case": "wrong_schema_lifeline_command_vocabulary"' },
        @{ Suffix = "substituted_command_vocab_case"; Needle = '"case": "substituted_lifeline_command_vocabulary"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "all_isolation_missing_case"; Needle = '"case": "loader_runtime_isolation_missing"' },
        @{ Suffix = "address_space_case"; Needle = '"case": "loader_address_space_boundary_missing"' },
        @{ Suffix = "entrypoint_case"; Needle = '"case": "loader_entrypoint_abi_missing"' },
        @{ Suffix = "memory_map_case"; Needle = '"case": "loader_memory_map_constraints_missing"' },
        @{ Suffix = "import_table_case"; Needle = '"case": "loader_capability_import_table_missing"' },
        @{ Suffix = "artifact_hash_case"; Needle = '"case": "loader_artifact_hash_binding_missing"' },
        @{ Suffix = "provider_sep_case"; Needle = '"case": "loader_provider_separation_missing"' },
        @{ Suffix = "normal_module_sep_case"; Needle = '"case": "loader_normal_module_separation_missing"' },
        @{ Suffix = "rollback_engine_case"; Needle = '"case": "rollback_transaction_engine_missing"' },
        @{ Suffix = "durable_case"; Needle = '"case": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_loader_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "recovery_loader_runtime_behavior_not_implemented"' },
        @{ Suffix = "loader_execution_false"; Needle = '"loader_execution_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.rollback_transaction_engine" -ExpectedMarker "RAIOS_AGENT_END recovery.rollback_transaction_engine"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_rollback_transaction_engine_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_rollback_transaction_engine.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_rollback_transaction_engine_records": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_transaction_envelope"; Needle = '"accepts_rollback_transaction_envelope": false' },
        @{ Suffix = "no_plan_json"; Needle = '"accepts_rollback_plan_json": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_envelope_exposed": true' },
        @{ Suffix = "vocab_not_accepted"; Needle = '"command_vocabulary_accepted": false' },
        @{ Suffix = "loader_boundary_exposed"; Needle = '"loader_runtime_isolation_boundary_exposed": true' },
        @{ Suffix = "loader_not_accepted"; Needle = '"loader_runtime_isolation_accepted": false' },
        @{ Suffix = "requirements_exposed"; Needle = '"transaction_requirements_exposed": true' },
        @{ Suffix = "engine_not_ready"; Needle = '"rollback_transaction_engine_ready": false' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "command_vocab_schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary.v0"' },
        @{ Suffix = "command_vocab_envelope"; Needle = '"state": "defined_read_only_envelope"' },
        @{ Suffix = "loader_boundary_schema"; Needle = '"schema": "raios.recovery_loader_runtime_isolation.v0"' },
        @{ Suffix = "loader_state"; Needle = '"state": "defined_non_executable"' },
        @{ Suffix = "target_selection_schema"; Needle = '"schema": "raios.recovery_rollback_target_selection.v0"' },
        @{ Suffix = "transaction_provenance_schema"; Needle = '"schema": "raios.recovery_rollback_transaction_provenance.v0"' },
        @{ Suffix = "last_good_schema"; Needle = '"schema": "raios.recovery_rollback_last_good_binding.v0"' },
        @{ Suffix = "disabled_set_schema"; Needle = '"schema": "raios.recovery_rollback_disabled_module_set_binding.v0"' },
        @{ Suffix = "artifact_hash_schema"; Needle = '"schema": "raios.recovery_rollback_artifact_hash_binding.v0"' },
        @{ Suffix = "replay_schema"; Needle = '"schema": "raios.recovery_rollback_replay_preconditions.v0"' },
        @{ Suffix = "capability_import_schema"; Needle = '"schema": "raios.recovery_rollback_recovery_capability_import.v0"' },
        @{ Suffix = "atomic_semantics_schema"; Needle = '"schema": "raios.recovery_rollback_atomic_apply_abort_semantics.v0"' },
        @{ Suffix = "target_selection_missing"; Needle = '"reason": "recovery_rollback_target_selection_missing"' },
        @{ Suffix = "transaction_provenance_missing"; Needle = '"reason": "recovery_rollback_transaction_id_provenance_missing"' },
        @{ Suffix = "last_good_missing"; Needle = '"reason": "recovery_rollback_last_good_binding_missing"' },
        @{ Suffix = "disabled_set_missing"; Needle = '"reason": "recovery_rollback_disabled_module_set_binding_missing"' },
        @{ Suffix = "artifact_hash_missing"; Needle = '"reason": "recovery_rollback_artifact_hash_binding_missing"' },
        @{ Suffix = "replay_missing"; Needle = '"reason": "recovery_rollback_replay_preconditions_missing"' },
        @{ Suffix = "capability_import_missing"; Needle = '"reason": "recovery_rollback_recovery_capability_import_missing"' },
        @{ Suffix = "atomic_semantics_missing"; Needle = '"reason": "recovery_rollback_atomic_apply_abort_semantics_missing"' },
        @{ Suffix = "durable_schema"; Needle = '"schema": "raios.durable_audit_rollback_persistence.v0"' },
        @{ Suffix = "durable_missing"; Needle = '"reason": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_schema"; Needle = '"schema": "raios.recovery_memory_provenance.v0"' },
        @{ Suffix = "memory_missing"; Needle = '"reason": "recovery_memory_provenance_missing"' },
        @{ Suffix = "preview_false"; Needle = '"rollback_preview_enabled": false' },
        @{ Suffix = "apply_false"; Needle = '"rollback_apply_enabled": false' },
        @{ Suffix = "execute_preview_false"; Needle = '"executes_rollback_preview": false' },
        @{ Suffix = "execute_apply_false"; Needle = '"executes_rollback_apply": false' },
        @{ Suffix = "no_loader_load"; Needle = '"loads_recovery_loader": false' },
        @{ Suffix = "no_artifact_load"; Needle = '"loads_recovery_artifact": false' },
        @{ Suffix = "no_authority"; Needle = '"authorizes_recovery_load": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryRollbackTransactionEngineResponse = Get-LastAgentResponseJson -Method "recovery.rollback_transaction_engine"
    $recoveryRollbackTransactionEngineRequestEventId = [string]$recoveryRollbackTransactionEngineResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryRollbackTransactionEngineRequestMatches = $recoveryRollbackTransactionEngineRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_rollback_transaction_engine_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryRollbackTransactionEngineRequestMatches -Actual $recoveryRollbackTransactionEngineRequestEventId
    if (-not $recoveryRollbackTransactionEngineRequestMatches) {
        throw "Expected recovery rollback transaction engine request event id $recoveryLifelineRequestEventId, got $recoveryRollbackTransactionEngineRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.rollback_transaction_engine_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.rollback_transaction_engine_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_rollback_transaction_engine_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_rollback_transaction_engine_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_rollback_transaction_engine_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 38' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "stale_request_case"; Needle = '"case": "stale_dropped_lifeline_request_event_id"' },
        @{ Suffix = "previous_request_case"; Needle = '"case": "previous_boot_lifeline_request_event_id"' },
        @{ Suffix = "wrong_request_schema_case"; Needle = '"case": "wrong_schema_lifeline_request_event_id"' },
        @{ Suffix = "substituted_request_case"; Needle = '"case": "substituted_lifeline_request_record"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "missing_protocol_state_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "previous_protocol_state_case"; Needle = '"case": "previous_boot_lifeline_protocol_state"' },
        @{ Suffix = "wrong_protocol_state_schema_case"; Needle = '"case": "wrong_schema_lifeline_protocol_state"' },
        @{ Suffix = "substituted_protocol_state_case"; Needle = '"case": "substituted_lifeline_protocol_state"' },
        @{ Suffix = "missing_command_vocab_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "previous_command_vocab_case"; Needle = '"case": "previous_boot_lifeline_command_vocabulary"' },
        @{ Suffix = "wrong_command_vocab_case"; Needle = '"case": "wrong_schema_lifeline_command_vocabulary"' },
        @{ Suffix = "substituted_command_vocab_case"; Needle = '"case": "substituted_lifeline_command_vocabulary"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "isolation_missing_case"; Needle = '"case": "loader_runtime_isolation_missing_after_command_vocabulary"' },
        @{ Suffix = "previous_isolation_case"; Needle = '"case": "previous_boot_loader_runtime_isolation"' },
        @{ Suffix = "wrong_isolation_schema_case"; Needle = '"case": "wrong_schema_loader_runtime_isolation"' },
        @{ Suffix = "substituted_isolation_case"; Needle = '"case": "substituted_loader_runtime_isolation"' },
        @{ Suffix = "address_space_case"; Needle = '"case": "loader_address_space_boundary_missing"' },
        @{ Suffix = "entrypoint_case"; Needle = '"case": "loader_entrypoint_abi_missing"' },
        @{ Suffix = "memory_map_case"; Needle = '"case": "loader_memory_map_constraints_missing"' },
        @{ Suffix = "import_table_case"; Needle = '"case": "loader_capability_import_table_missing"' },
        @{ Suffix = "loader_artifact_hash_case"; Needle = '"case": "loader_artifact_hash_binding_missing"' },
        @{ Suffix = "provider_sep_case"; Needle = '"case": "loader_provider_separation_missing"' },
        @{ Suffix = "normal_module_sep_case"; Needle = '"case": "loader_normal_module_separation_missing"' },
        @{ Suffix = "engine_missing_case"; Needle = '"case": "rollback_transaction_engine_missing"' },
        @{ Suffix = "target_selection_case"; Needle = '"case": "rollback_target_selection_missing"' },
        @{ Suffix = "transaction_provenance_case"; Needle = '"case": "rollback_transaction_id_provenance_missing"' },
        @{ Suffix = "last_good_case"; Needle = '"case": "rollback_last_good_binding_missing"' },
        @{ Suffix = "disabled_set_case"; Needle = '"case": "rollback_disabled_module_set_binding_missing"' },
        @{ Suffix = "artifact_hash_case"; Needle = '"case": "rollback_artifact_hash_binding_missing"' },
        @{ Suffix = "replay_case"; Needle = '"case": "rollback_replay_preconditions_missing"' },
        @{ Suffix = "capability_import_case"; Needle = '"case": "rollback_recovery_capability_import_missing"' },
        @{ Suffix = "atomic_semantics_case"; Needle = '"case": "rollback_atomic_apply_abort_semantics_missing"' },
        @{ Suffix = "durable_case"; Needle = '"case": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_rollback_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "recovery_rollback_transaction_behavior_not_implemented"' },
        @{ Suffix = "preview_false"; Needle = '"rollback_preview_enabled": false' },
        @{ Suffix = "apply_false"; Needle = '"rollback_apply_enabled": false' },
        @{ Suffix = "execution_false"; Needle = '"command_execution_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.durable_audit_rollback_persistence" -ExpectedMarker "RAIOS_AGENT_END recovery.durable_audit_rollback_persistence"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_durable_audit_rollback_persistence_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.durable_audit_rollback_persistence.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_durable_audit_rollback_persistence_records": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_transaction_envelope"; Needle = '"accepts_rollback_transaction_envelope": false' },
        @{ Suffix = "no_plan_json"; Needle = '"accepts_rollback_plan_json": false' },
        @{ Suffix = "no_request_json"; Needle = '"accepts_lifeline_request_json": false' },
        @{ Suffix = "no_loader_descriptor"; Needle = '"accepts_loader_descriptor": false' },
        @{ Suffix = "no_artifact_bytes"; Needle = '"accepts_artifact_bytes": false' },
        @{ Suffix = "no_device_json"; Needle = '"accepts_persistence_device_inventory_json": false' },
        @{ Suffix = "no_layout_json"; Needle = '"accepts_storage_layout_json": false' },
        @{ Suffix = "no_memory_record"; Needle = '"accepts_recovery_memory_record": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_envelope_exposed": true' },
        @{ Suffix = "vocab_not_accepted"; Needle = '"command_vocabulary_accepted": false' },
        @{ Suffix = "loader_boundary_exposed"; Needle = '"loader_runtime_isolation_boundary_exposed": true' },
        @{ Suffix = "loader_not_accepted"; Needle = '"loader_runtime_isolation_accepted": false' },
        @{ Suffix = "engine_boundary_exposed"; Needle = '"rollback_transaction_engine_boundary_exposed": true' },
        @{ Suffix = "engine_not_accepted"; Needle = '"rollback_transaction_engine_accepted": false' },
        @{ Suffix = "requirements_exposed"; Needle = '"persistence_requirements_exposed": true' },
        @{ Suffix = "persistence_not_ready"; Needle = '"durable_audit_rollback_persistence_ready": false' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "command_vocab_schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary.v0"' },
        @{ Suffix = "loader_boundary_schema"; Needle = '"schema": "raios.recovery_loader_runtime_isolation.v0"' },
        @{ Suffix = "transaction_boundary_schema"; Needle = '"schema": "raios.recovery_rollback_transaction_engine.v0"' },
        @{ Suffix = "persistence_device_schema"; Needle = '"schema": "raios.persistence_device_inventory.v0"' },
        @{ Suffix = "storage_layout_schema"; Needle = '"schema": "raios.durable_audit_rollback_storage_layout_identity.v0"' },
        @{ Suffix = "audit_log_schema"; Needle = '"schema": "raios.durable_audit_append_log_identity.v0"' },
        @{ Suffix = "rollback_store_schema"; Needle = '"schema": "raios.rollback_store_identity.v0"' },
        @{ Suffix = "replay_cursor_schema"; Needle = '"schema": "raios.rollback_transaction_replay_cursor.v0"' },
        @{ Suffix = "checkpoint_schema"; Needle = '"schema": "raios.recovery_last_good_checkpoint_binding.v0"' },
        @{ Suffix = "write_ordering_schema"; Needle = '"schema": "raios.durable_write_ordering.v0"' },
        @{ Suffix = "crash_schema"; Needle = '"schema": "raios.durable_crash_consistency.v0"' },
        @{ Suffix = "integrity_schema"; Needle = '"schema": "raios.durable_integrity_root_hash_chain.v0"' },
        @{ Suffix = "memory_schema"; Needle = '"schema": "raios.recovery_memory_provenance.v0"' },
        @{ Suffix = "persistence_device_missing"; Needle = '"reason": "persistence_device_inventory_missing"' },
        @{ Suffix = "storage_layout_missing"; Needle = '"reason": "durable_storage_layout_identity_missing"' },
        @{ Suffix = "audit_log_missing"; Needle = '"reason": "durable_audit_append_log_identity_missing"' },
        @{ Suffix = "rollback_store_missing"; Needle = '"reason": "rollback_store_identity_missing"' },
        @{ Suffix = "replay_cursor_missing"; Needle = '"reason": "rollback_transaction_replay_cursor_missing"' },
        @{ Suffix = "checkpoint_missing"; Needle = '"reason": "recovery_last_good_checkpoint_binding_missing"' },
        @{ Suffix = "write_ordering_missing"; Needle = '"reason": "durable_write_ordering_missing"' },
        @{ Suffix = "crash_missing"; Needle = '"reason": "durable_crash_consistency_missing"' },
        @{ Suffix = "integrity_missing"; Needle = '"reason": "durable_integrity_root_hash_chain_missing"' },
        @{ Suffix = "memory_missing"; Needle = '"reason": "recovery_memory_provenance_missing"' },
        @{ Suffix = "durable_writes_false"; Needle = '"durable_writes_enabled": false' },
        @{ Suffix = "replay_false"; Needle = '"rollback_replay_enabled": false' },
        @{ Suffix = "memory_writes_false"; Needle = '"recovery_memory_writes_enabled": false' },
        @{ Suffix = "preview_false"; Needle = '"rollback_preview_enabled": false' },
        @{ Suffix = "apply_false"; Needle = '"rollback_apply_enabled": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryDurablePersistenceResponse = Get-LastAgentResponseJson -Method "recovery.durable_audit_rollback_persistence"
    $recoveryDurablePersistenceRequestEventId = [string]$recoveryDurablePersistenceResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryDurablePersistenceRequestMatches = $recoveryDurablePersistenceRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_durable_audit_rollback_persistence_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryDurablePersistenceRequestMatches -Actual $recoveryDurablePersistenceRequestEventId
    if (-not $recoveryDurablePersistenceRequestMatches) {
        throw "Expected recovery durable persistence request event id $recoveryLifelineRequestEventId, got $recoveryDurablePersistenceRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.durable_audit_rollback_persistence_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.durable_audit_rollback_persistence_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_durable_audit_rollback_persistence_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.durable_audit_rollback_persistence_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_durable_audit_rollback_persistence_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 51' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "protocol_state_missing_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "missing_command_vocab_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "isolation_missing_case"; Needle = '"case": "loader_runtime_isolation_missing_after_command_vocabulary"' },
        @{ Suffix = "substituted_isolation_case"; Needle = '"case": "substituted_loader_runtime_isolation"' },
        @{ Suffix = "address_space_case"; Needle = '"case": "loader_address_space_boundary_missing"' },
        @{ Suffix = "engine_boundary_missing_case"; Needle = '"case": "rollback_transaction_engine_boundary_missing_after_loader"' },
        @{ Suffix = "previous_engine_case"; Needle = '"case": "previous_boot_rollback_transaction_engine"' },
        @{ Suffix = "wrong_engine_schema_case"; Needle = '"case": "wrong_schema_rollback_transaction_engine"' },
        @{ Suffix = "substituted_engine_case"; Needle = '"case": "substituted_rollback_transaction_engine"' },
        @{ Suffix = "mismatched_engine_case"; Needle = '"case": "mismatched_rollback_transaction_engine"' },
        @{ Suffix = "target_selection_case"; Needle = '"case": "rollback_target_selection_missing"' },
        @{ Suffix = "transaction_provenance_case"; Needle = '"case": "rollback_transaction_id_provenance_missing"' },
        @{ Suffix = "atomic_semantics_case"; Needle = '"case": "rollback_atomic_apply_abort_semantics_missing"' },
        @{ Suffix = "persistence_missing_case"; Needle = '"case": "durable_audit_rollback_persistence_missing"' },
        @{ Suffix = "device_case"; Needle = '"case": "persistence_device_inventory_missing"' },
        @{ Suffix = "storage_layout_case"; Needle = '"case": "storage_layout_identity_missing"' },
        @{ Suffix = "audit_log_case"; Needle = '"case": "audit_append_log_identity_missing"' },
        @{ Suffix = "rollback_store_case"; Needle = '"case": "rollback_store_identity_missing"' },
        @{ Suffix = "replay_cursor_case"; Needle = '"case": "transaction_replay_cursor_missing"' },
        @{ Suffix = "checkpoint_case"; Needle = '"case": "last_good_checkpoint_binding_missing"' },
        @{ Suffix = "write_ordering_case"; Needle = '"case": "write_ordering_missing"' },
        @{ Suffix = "crash_case"; Needle = '"case": "crash_consistency_missing"' },
        @{ Suffix = "integrity_case"; Needle = '"case": "integrity_root_hash_chain_missing"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_persistence_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "durable_audit_rollback_persistence_behavior_not_implemented"' },
        @{ Suffix = "durable_writes_false"; Needle = '"durable_writes_enabled": false' },
        @{ Suffix = "replay_false"; Needle = '"rollback_replay_enabled": false' },
        @{ Suffix = "memory_writes_false"; Needle = '"recovery_memory_writes_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.memory_provenance" -ExpectedMarker "RAIOS_AGENT_END recovery.memory_provenance"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_memory_provenance_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_memory_provenance.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_memory_provenance_records": false' },
        @{ Suffix = "no_memory_json"; Needle = '"accepts_memory_record_json": false' },
        @{ Suffix = "no_memory_record"; Needle = '"accepts_recovery_memory_record": false' },
        @{ Suffix = "no_provider_export_accept"; Needle = '"accepts_provider_context_export": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_transaction_envelope"; Needle = '"accepts_rollback_transaction_envelope": false' },
        @{ Suffix = "no_device_json"; Needle = '"accepts_persistence_device_inventory_json": false' },
        @{ Suffix = "no_memory_write"; Needle = '"writes_recovery_memory": false' },
        @{ Suffix = "no_provider_export"; Needle = '"exports_provider_context": false' },
        @{ Suffix = "no_durable_write"; Needle = '"writes_durable_audit_log": false' },
        @{ Suffix = "no_rollback_store"; Needle = '"writes_rollback_store": false' },
        @{ Suffix = "no_replay"; Needle = '"replays_rollback_transactions": false' },
        @{ Suffix = "no_openai_shortcut"; Needle = '"uses_direct_openai_recovery_path": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_envelope_exposed": true' },
        @{ Suffix = "vocab_not_accepted"; Needle = '"command_vocabulary_accepted": false' },
        @{ Suffix = "loader_boundary_exposed"; Needle = '"loader_runtime_isolation_boundary_exposed": true' },
        @{ Suffix = "loader_not_accepted"; Needle = '"loader_runtime_isolation_accepted": false' },
        @{ Suffix = "engine_boundary_exposed"; Needle = '"rollback_transaction_engine_boundary_exposed": true' },
        @{ Suffix = "engine_not_accepted"; Needle = '"rollback_transaction_engine_accepted": false' },
        @{ Suffix = "durable_boundary_exposed"; Needle = '"durable_audit_rollback_persistence_boundary_exposed": true' },
        @{ Suffix = "durable_not_accepted"; Needle = '"durable_audit_rollback_persistence_accepted": false' },
        @{ Suffix = "requirements_exposed"; Needle = '"memory_provenance_requirements_exposed": true' },
        @{ Suffix = "memory_not_ready"; Needle = '"recovery_memory_provenance_ready": false' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "identity_event"; Needle = "`"retained_recovery_artifact_identity_event_id`": `"$recoveryIdentityEventId`"" },
        @{ Suffix = "rollback_event"; Needle = "`"retained_recovery_artifact_rollback_evidence_event_id`": `"$recoveryRollbackEvidenceEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "command_vocab_schema"; Needle = '"schema": "raios.recovery_lifeline_command_vocabulary.v0"' },
        @{ Suffix = "loader_boundary_schema"; Needle = '"schema": "raios.recovery_loader_runtime_isolation.v0"' },
        @{ Suffix = "transaction_boundary_schema"; Needle = '"schema": "raios.recovery_rollback_transaction_engine.v0"' },
        @{ Suffix = "durable_boundary_schema"; Needle = '"schema": "raios.durable_audit_rollback_persistence.v0"' },
        @{ Suffix = "source_ids_schema"; Needle = '"schema": "raios.recovery_memory_source_record_ids.v0"' },
        @{ Suffix = "source_hashes_schema"; Needle = '"schema": "raios.recovery_memory_source_schema_hashes.v0"' },
        @{ Suffix = "classification_schema"; Needle = '"schema": "raios.recovery_memory_classification.v0"' },
        @{ Suffix = "authority_schema"; Needle = '"schema": "raios.recovery_memory_authority_level.v0"' },
        @{ Suffix = "rollback_binding_schema"; Needle = '"schema": "raios.recovery_memory_rollback_transaction_binding.v0"' },
        @{ Suffix = "checkpoint_binding_schema"; Needle = '"schema": "raios.recovery_memory_last_good_checkpoint_binding.v0"' },
        @{ Suffix = "export_profile_schema"; Needle = '"schema": "raios.recovery_memory_export_profile.v0"' },
        @{ Suffix = "redaction_schema"; Needle = '"schema": "raios.recovery_memory_redaction_state.v0"' },
        @{ Suffix = "replay_window_schema"; Needle = '"schema": "raios.recovery_memory_replay_window.v0"' },
        @{ Suffix = "audit_linkage_schema"; Needle = '"schema": "raios.recovery_memory_audit_linkage.v0"' },
        @{ Suffix = "source_ids_missing"; Needle = '"reason": "recovery_memory_source_record_ids_missing"' },
        @{ Suffix = "source_hashes_missing"; Needle = '"reason": "recovery_memory_source_schema_hashes_missing"' },
        @{ Suffix = "classification_missing"; Needle = '"reason": "recovery_memory_classification_missing"' },
        @{ Suffix = "authority_missing"; Needle = '"reason": "recovery_memory_authority_level_missing"' },
        @{ Suffix = "rollback_binding_missing"; Needle = '"reason": "recovery_memory_rollback_transaction_binding_missing"' },
        @{ Suffix = "checkpoint_binding_missing"; Needle = '"reason": "recovery_memory_last_good_checkpoint_binding_missing"' },
        @{ Suffix = "export_profile_missing"; Needle = '"reason": "recovery_only_export_profile_missing"' },
        @{ Suffix = "redaction_missing"; Needle = '"reason": "recovery_memory_redaction_state_missing"' },
        @{ Suffix = "replay_window_missing"; Needle = '"reason": "recovery_memory_replay_window_missing"' },
        @{ Suffix = "audit_linkage_missing"; Needle = '"reason": "recovery_memory_audit_linkage_missing"' },
        @{ Suffix = "memory_writes_false"; Needle = '"memory_writes_enabled": false' },
        @{ Suffix = "provider_export_false"; Needle = '"provider_export_enabled": false' },
        @{ Suffix = "durable_writes_false"; Needle = '"durable_writes_enabled": false' },
        @{ Suffix = "replay_false"; Needle = '"rollback_replay_enabled": false' },
        @{ Suffix = "recovery_memory_writes_false"; Needle = '"recovery_memory_writes_enabled": false' },
        @{ Suffix = "preview_false"; Needle = '"rollback_preview_enabled": false' },
        @{ Suffix = "apply_false"; Needle = '"rollback_apply_enabled": false' },
        @{ Suffix = "no_durable"; Needle = '"creates_durable_records": false' },
        @{ Suffix = "no_install"; Needle = '"installs_rollback_plan": false' },
        @{ Suffix = "no_slot"; Needle = '"allocates_service_slot": false' },
        @{ Suffix = "no_service_change"; Needle = '"service_inventory_change": "none"' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryMemoryProvenanceResponse = Get-LastAgentResponseJson -Method "recovery.memory_provenance"
    $recoveryMemoryProvenanceRequestEventId = [string]$recoveryMemoryProvenanceResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryMemoryProvenanceRequestMatches = $recoveryMemoryProvenanceRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_memory_provenance_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryMemoryProvenanceRequestMatches -Actual $recoveryMemoryProvenanceRequestEventId
    if (-not $recoveryMemoryProvenanceRequestMatches) {
        throw "Expected recovery memory provenance request event id $recoveryLifelineRequestEventId, got $recoveryMemoryProvenanceRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.memory_provenance_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.memory_provenance_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_memory_provenance_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_memory_provenance_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_memory_provenance_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 65' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "protocol_state_missing_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "missing_command_vocab_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "isolation_missing_case"; Needle = '"case": "loader_runtime_isolation_missing_after_command_vocabulary"' },
        @{ Suffix = "substituted_isolation_case"; Needle = '"case": "substituted_loader_runtime_isolation"' },
        @{ Suffix = "engine_boundary_missing_case"; Needle = '"case": "rollback_transaction_engine_boundary_missing_after_loader"' },
        @{ Suffix = "mismatched_engine_case"; Needle = '"case": "mismatched_rollback_transaction_engine"' },
        @{ Suffix = "durable_missing_case"; Needle = '"case": "durable_persistence_boundary_missing_after_rollback_engine"' },
        @{ Suffix = "previous_durable_case"; Needle = '"case": "previous_boot_durable_persistence"' },
        @{ Suffix = "mismatched_durable_case"; Needle = '"case": "mismatched_durable_persistence"' },
        @{ Suffix = "device_case"; Needle = '"case": "persistence_device_inventory_missing"' },
        @{ Suffix = "integrity_case"; Needle = '"case": "integrity_root_hash_chain_missing"' },
        @{ Suffix = "memory_provenance_case"; Needle = '"case": "recovery_memory_provenance_missing"' },
        @{ Suffix = "source_ids_case"; Needle = '"case": "source_record_ids_missing"' },
        @{ Suffix = "schema_hashes_case"; Needle = '"case": "source_schema_hashes_missing"' },
        @{ Suffix = "classification_case"; Needle = '"case": "memory_classification_missing"' },
        @{ Suffix = "authority_case"; Needle = '"case": "memory_authority_level_missing"' },
        @{ Suffix = "rollback_binding_case"; Needle = '"case": "memory_rollback_transaction_binding_missing"' },
        @{ Suffix = "checkpoint_binding_case"; Needle = '"case": "memory_last_good_checkpoint_binding_missing"' },
        @{ Suffix = "export_profile_case"; Needle = '"case": "recovery_only_export_profile_missing"' },
        @{ Suffix = "redaction_case"; Needle = '"case": "memory_redaction_state_missing"' },
        @{ Suffix = "replay_window_case"; Needle = '"case": "memory_replay_window_missing"' },
        @{ Suffix = "audit_linkage_case"; Needle = '"case": "memory_audit_linkage_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_memory_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "recovery_memory_provenance_behavior_not_implemented"' },
        @{ Suffix = "memory_writes_false"; Needle = '"memory_writes_enabled": false' },
        @{ Suffix = "provider_export_false"; Needle = '"provider_export_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )

    Send-AgentCommand -Command "agent recovery.lifeline_command_admission" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_command_admission"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_command_admission_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_command_admission.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "status"; Needle = '"status": "denied_missing_lifeline_protocol_state"' },
        @{ Suffix = "reason"; Needle = '"reason": "recovery_lifeline_protocol_state_missing"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_command_admission_records": false' },
        @{ Suffix = "no_command_envelope"; Needle = '"accepts_lifeline_command_envelope": false' },
        @{ Suffix = "no_dispatch"; Needle = '"dispatches_lifeline_command": false' },
        @{ Suffix = "no_status_exec"; Needle = '"executes_lifeline_status": false' },
        @{ Suffix = "no_preview"; Needle = '"executes_rollback_preview": false' },
        @{ Suffix = "no_apply"; Needle = '"executes_rollback_apply": false' },
        @{ Suffix = "no_disable"; Needle = '"executes_disable_module": false' },
        @{ Suffix = "no_restart"; Needle = '"executes_restart_last_good": false' },
        @{ Suffix = "no_load_by_hash"; Needle = '"executes_load_recovery_artifact_by_hash": false' },
        @{ Suffix = "request_valid"; Needle = '"request_chain_valid": true' },
        @{ Suffix = "vocab_exposed"; Needle = '"command_vocabulary_envelope_exposed": true' },
        @{ Suffix = "loader_boundary_exposed"; Needle = '"loader_runtime_isolation_boundary_exposed": true' },
        @{ Suffix = "engine_boundary_exposed"; Needle = '"rollback_transaction_engine_boundary_exposed": true' },
        @{ Suffix = "durable_boundary_exposed"; Needle = '"durable_audit_rollback_persistence_boundary_exposed": true' },
        @{ Suffix = "memory_boundary_exposed"; Needle = '"recovery_memory_provenance_boundary_exposed": true' },
        @{ Suffix = "memory_not_accepted"; Needle = '"recovery_memory_provenance_accepted": false' },
        @{ Suffix = "requirements_not_exposed"; Needle = '"command_admission_requirements_exposed": false' },
        @{ Suffix = "admission_not_ready"; Needle = '"command_admission_ready": false' },
        @{ Suffix = "status_command"; Needle = '"command_id": "recovery.lifeline.status"' },
        @{ Suffix = "preview_command"; Needle = '"command_id": "recovery.lifeline.rollback_preview"' },
        @{ Suffix = "apply_command"; Needle = '"command_id": "recovery.lifeline.rollback_apply"' },
        @{ Suffix = "disable_command"; Needle = '"command_id": "recovery.lifeline.disable_module"' },
        @{ Suffix = "restart_command"; Needle = '"command_id": "recovery.lifeline.restart_last_good"' },
        @{ Suffix = "load_hash_command"; Needle = '"command_id": "recovery.lifeline.load_artifact_by_hash"' },
        @{ Suffix = "status_schema"; Needle = '"admission_schema": "raios.recovery_lifeline_status_admission.v0"' },
        @{ Suffix = "preview_schema"; Needle = '"admission_schema": "raios.recovery_rollback_preview_admission.v0"' },
        @{ Suffix = "apply_schema"; Needle = '"admission_schema": "raios.recovery_rollback_apply_admission.v0"' },
        @{ Suffix = "disable_schema"; Needle = '"admission_schema": "raios.recovery_disable_module_admission.v0"' },
        @{ Suffix = "restart_schema"; Needle = '"admission_schema": "raios.recovery_restart_last_good_admission.v0"' },
        @{ Suffix = "load_hash_schema"; Needle = '"admission_schema": "raios.recovery_load_artifact_by_hash_admission.v0"' },
        @{ Suffix = "request_event"; Needle = "`"event_id`": `"$recoveryLifelineRequestEventId`"" },
        @{ Suffix = "request_hash"; Needle = "`"lifeline_request_reference_hash`": `"sha256:$recoveryLifelineRequestReferenceHash`"" },
        @{ Suffix = "command_execution_false"; Needle = '"command_execution_enabled": false' },
        @{ Suffix = "provider_export_false"; Needle = '"provider_export_enabled": false' },
        @{ Suffix = "durable_writes_false"; Needle = '"durable_writes_enabled": false' },
        @{ Suffix = "memory_writes_false"; Needle = '"memory_writes_enabled": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
    $recoveryCommandAdmissionResponse = Get-LastAgentResponseJson -Method "recovery.lifeline_command_admission"
    $recoveryCommandAdmissionRequestEventId = [string]$recoveryCommandAdmissionResponse.body.result.retained_recovery_lifeline_request.event_id
    $recoveryCommandAdmissionRequestMatches = $recoveryCommandAdmissionRequestEventId -eq $recoveryLifelineRequestEventId
    Add-Predicate -Name "protocol:recovery_lifeline_command_admission_request_event_id_matches_retained" -Expected $recoveryLifelineRequestEventId -Passed $recoveryCommandAdmissionRequestMatches -Actual $recoveryCommandAdmissionRequestEventId
    if (-not $recoveryCommandAdmissionRequestMatches) {
        throw "Expected recovery command-admission request event id $recoveryLifelineRequestEventId, got $recoveryCommandAdmissionRequestEventId"
    }

    Send-AgentCommand -Command "agent recovery.lifeline_command_admission_selftest" -ExpectedMarker "RAIOS_AGENT_END recovery.lifeline_command_admission_selftest"
    Assert-LogContainsFields -NamePrefix "protocol:recovery_lifeline_command_admission_selftest_" -TimeoutSeconds 1 -Fields @(
        @{ Suffix = "schema"; Needle = '"schema": "raios.recovery_lifeline_command_admission_selftest.v0"' },
        @{ Suffix = "local_only"; Needle = '"classification": "local_only"' },
        @{ Suffix = "no_mutation"; Needle = '"mutates_global_event_log": false' },
        @{ Suffix = "no_records"; Needle = '"creates_retained_recovery_lifeline_command_admission_records": false' },
        @{ Suffix = "case_count"; Needle = '"case_count": 45' },
        @{ Suffix = "passed"; Needle = '"passed": true' },
        @{ Suffix = "missing_request_case"; Needle = '"case": "missing_lifeline_request_event_id"' },
        @{ Suffix = "request_hash_case"; Needle = '"case": "lifeline_request_reference_hash_mismatch"' },
        @{ Suffix = "protocol_state_missing_case"; Needle = '"case": "protocol_state_missing_after_valid_request"' },
        @{ Suffix = "command_vocab_missing_case"; Needle = '"case": "command_vocabulary_missing_after_protocol_state"' },
        @{ Suffix = "direct_openai_case"; Needle = '"case": "direct_openai_recovery_shortcut_rejected"' },
        @{ Suffix = "loader_mismatch_case"; Needle = '"case": "mismatched_loader_runtime_isolation"' },
        @{ Suffix = "engine_mismatch_case"; Needle = '"case": "mismatched_rollback_transaction_engine"' },
        @{ Suffix = "durable_mismatch_case"; Needle = '"case": "mismatched_durable_persistence"' },
        @{ Suffix = "memory_boundary_case"; Needle = '"case": "recovery_memory_provenance_boundary_missing"' },
        @{ Suffix = "memory_mismatch_case"; Needle = '"case": "mismatched_recovery_memory_provenance"' },
        @{ Suffix = "memory_facts_case"; Needle = '"case": "recovery_memory_provenance_facts_missing"' },
        @{ Suffix = "admission_missing_case"; Needle = '"case": "command_admission_requirements_missing"' },
        @{ Suffix = "status_missing_case"; Needle = '"case": "lifeline_status_command_admission_missing"' },
        @{ Suffix = "preview_missing_case"; Needle = '"case": "rollback_preview_command_admission_missing"' },
        @{ Suffix = "apply_missing_case"; Needle = '"case": "rollback_apply_command_admission_missing"' },
        @{ Suffix = "disable_missing_case"; Needle = '"case": "disable_module_command_admission_missing"' },
        @{ Suffix = "restart_missing_case"; Needle = '"case": "restart_last_good_command_admission_missing"' },
        @{ Suffix = "load_hash_missing_case"; Needle = '"case": "load_artifact_by_hash_command_admission_missing"' },
        @{ Suffix = "non_executable_case"; Needle = '"case": "all_inputs_present_command_admission_still_non_executable"' },
        @{ Suffix = "non_executable_reason"; Needle = '"actual_reason": "recovery_lifeline_command_admission_behavior_not_implemented"' },
        @{ Suffix = "command_execution_false"; Needle = '"command_execution_enabled": false' },
        @{ Suffix = "dispatch_false"; Needle = '"dispatches_lifeline_command": false' },
        @{ Suffix = "load_attempted_false"; Needle = '"load_attempted": false' }
    )
