use super::*;

#[derive(Clone, Copy)]
pub(crate) struct LoadDescriptor {
    pub schema: &'static str,
    pub id: &'static str,
    pub canonicalization: &'static str,
    pub source_locator: &'static str,
    pub source_kind: &'static str,
    pub binds_source_locator: Option<&'static str>,
    pub binds_source_kind: Option<&'static str>,
    pub binds_source_hash: Option<[u8; 32]>,
    pub source_text: &'static str,
    pub source_envelope: Option<descriptor_sources::DescriptorSourceEnvelope>,
    pub artifact_identity: descriptor_sources::ArtifactIdentityRecord,
    pub service_id: &'static str,
    pub artifact_id: &'static str,
    pub artifact_kind: &'static str,
    pub scope: &'static str,
    pub classification: &'static str,
    pub persistence: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) struct ArtifactLoadPlanPreflightRecord {
    pub(crate) schema: &'static str,
    pub(crate) id: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) classification: &'static str,
    pub(crate) status: &'static str,
    pub(crate) preflight_hash: [u8; 32],
    pub(crate) service_id: &'static str,
    pub(crate) artifact_id: &'static str,
    pub(crate) load_descriptor_id: &'static str,
    pub(crate) descriptor_source_locator: &'static str,
    pub(crate) descriptor_source_hash: [u8; 32],
    pub(crate) artifact_identity_id: &'static str,
    pub(crate) artifact_identity_hash: [u8; 32],
    pub(crate) artifact_content_binding_hash: [u8; 32],
    pub(crate) artifact_reference_id: &'static str,
    pub(crate) artifact_reference_hash: [u8; 32],
    pub(crate) artifact_bytes_sha256: [u8; 32],
    pub(crate) service_slot_intent_schema: &'static str,
    pub(crate) service_slot_intent_id: &'static str,
    pub(crate) ram_only_service_slot_id: &'static str,
    pub(crate) accepted: bool,
    pub(crate) authorizes_builtin_current_boot_start: bool,
    pub(crate) authorizes_candidate_artifact_execution: bool,
    pub(crate) accepts_external_artifact_bytes: bool,
    pub(crate) loads_candidate_bytes: bool,
    pub(crate) maps_executable_pages: bool,
    pub(crate) writes_persistent_state: bool,
    pub(crate) writes_durable_audit_log: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) grants_broad_mutation: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackWriterStorageFoundation {
    pub(crate) storage_layout_status: &'static str,
    pub(crate) storage_layout_reason: &'static str,
    pub(crate) storage_layout_available: bool,
    pub(crate) append_engine_status: &'static str,
    pub(crate) append_engine_reason: &'static str,
    pub(crate) append_engine_available: bool,
    pub(crate) append_contract_status: &'static str,
    pub(crate) append_contract_reason: &'static str,
    pub(crate) rollback_transaction_envelope_status: &'static str,
    pub(crate) rollback_transaction_envelope_reason: &'static str,
    pub(crate) rollback_transaction_envelope_available: bool,
    pub(crate) append_target_owner_status: &'static str,
    pub(crate) append_target_owner_reason: &'static str,
    pub(crate) append_target_owner_available: bool,
    pub(crate) transaction_writer_status: &'static str,
    pub(crate) transaction_writer_reason: &'static str,
    pub(crate) transaction_writer_ready: bool,
    pub(crate) block_write_path_available: bool,
    pub(crate) block_write_path_reason: &'static str,
    pub(crate) block_write_path_gate_status: &'static str,
    pub(crate) read_only_block_driver_id: &'static str,
    pub(crate) read_only_block_driver_available: bool,
    pub(crate) partition_inventory_available: bool,
    pub(crate) partition_inventory_scheme: &'static str,
    pub(crate) target_region_discovery: rollback_storage_layout::AuditRollbackTargetRegionDiscovery,
    pub(crate) target_region_writer_contract_status: &'static str,
    pub(crate) target_region_writer_contract_reason: &'static str,
    pub(crate) target_region_writer_contract_ready: bool,
    pub(crate) target_region_media_write_policy_preflight_status: &'static str,
    pub(crate) target_region_media_write_policy_preflight_reason: &'static str,
    pub(crate) scratch_block_write_authority_id: &'static str,
    pub(crate) scratch_block_write_authority_available: bool,
    pub(crate) scratch_region_within_device_bounds: bool,
    pub(crate) scratch_region_no_boot_or_partition_metadata_overlap: bool,
    pub(crate) scratch_region_id: &'static str,
    pub(crate) scratch_region_start_lba: u64,
    pub(crate) scratch_region_lba_count: u64,
    pub(crate) scratch_region_byte_count: u32,
    pub(crate) scratch_writer_dry_run_status: &'static str,
    pub(crate) scratch_writer_dry_run_reason: &'static str,
    pub(crate) scratch_writer_dry_run_ready: bool,
    pub(crate) transaction_writer_available: bool,
    pub(crate) durable_audit_store_available: bool,
    pub(crate) rollback_store_available: bool,
    pub(crate) rollback_transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackAppendRecordDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) audit_record_image_hash: [u8; 32],
    pub(crate) rollback_transaction_image_hash: [u8; 32],
    pub(crate) audit_record_byte_length: u64,
    pub(crate) rollback_transaction_byte_length: u64,
    pub(crate) total_record_byte_length: u64,
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) target_range_ready: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackAppendSectorPlanDryRun {
    pub(crate) plan_hash: [u8; 32],
    pub(crate) sector_image_hash: [u8; 32],
    pub(crate) sector_size_bytes: u64,
    pub(crate) audit_record_offset: u64,
    pub(crate) audit_record_byte_length: u64,
    pub(crate) rollback_transaction_offset: u64,
    pub(crate) rollback_transaction_byte_length: u64,
    pub(crate) padding_offset: u64,
    pub(crate) padding_byte_length: u64,
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) target_range_ready: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackAppendSectorWriteReadbackDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_plan_hash: [u8; 32],
    pub(crate) planned_sector_image_hash: [u8; 32],
    pub(crate) readback_sector_image_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) label_found: bool,
    pub(crate) target_range_ready: bool,
    pub(crate) write_attempted: bool,
    pub(crate) write_completed: bool,
    pub(crate) readback_completed: bool,
    pub(crate) readback_matches_planned_image: bool,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) struct TargetRegionMediaWritePolicyPreflight {
    pub(crate) preflight_hash: [u8; 32],
    pub(crate) source_contract_status: &'static str,
    pub(crate) source_contract_reason: &'static str,
    pub(crate) source_contract_target_range_ready: bool,
    pub(crate) owner_ids_verified: bool,
    pub(crate) target_ids_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) schema_ids_verified: bool,
    pub(crate) target_region_start_lba: u64,
    pub(crate) target_region_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) media_write_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackMediaWriteAuthorityGate {
    pub(crate) gate_hash: [u8; 32],
    pub(crate) source_durable_append_authority_preflight_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) source_contract_status: &'static str,
    pub(crate) source_contract_reason: &'static str,
    pub(crate) source_contract_target_range_ready: bool,
    pub(crate) owner_ids_verified: bool,
    pub(crate) target_ids_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) schema_ids_verified: bool,
    pub(crate) target_region_start_lba: u64,
    pub(crate) target_region_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) media_write_authority_available: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) target_region_write_attempted: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAppendAuthorityDecision {
    pub(crate) decision_hash: [u8; 32],
    pub(crate) source_durable_append_authority_preflight_hash: [u8; 32],
    pub(crate) source_writer_policy_preflight_hash: [u8; 32],
    pub(crate) source_append_engine_readiness_decision_hash: [u8; 32],
    pub(crate) source_media_write_authority_gate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) writer_policy_ready: bool,
    pub(crate) append_engine_ready: bool,
    pub(crate) media_write_gate_ready: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyDecision {
    pub(crate) decision_hash: [u8; 32],
    pub(crate) source_durable_append_authority_decision_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_media_write_authority_gate_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) append_engine_ready: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyCandidate {
    pub(crate) candidate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_decision_hash: [u8; 32],
    pub(crate) source_audit_record_image_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) durable_audit_policy_candidate_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyAcceptanceGate {
    pub(crate) gate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_candidate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_decision_hash: [u8; 32],
    pub(crate) source_audit_record_image_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) candidate_available: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyLedgerCandidate {
    pub(crate) ledger_candidate_hash: [u8; 32],
    pub(crate) source_acceptance_gate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_candidate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_decision_hash: [u8; 32],
    pub(crate) source_audit_record_image_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) read_only_ledger_candidate_available: bool,
    pub(crate) candidate_available: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyLedgerAwareAcceptanceResult {
    pub(crate) result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_acceptance_gate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_candidate_hash: [u8; 32],
    pub(crate) source_durable_audit_policy_decision_hash: [u8; 32],
    pub(crate) source_audit_record_image_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) read_only_ledger_candidate_available: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyWriteAuthorityAvailability {
    pub(crate) availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurablePolicyLedgerAvailability {
    pub(crate) availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurablePolicyLedgerAvailabilityDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) source_authority_denial_gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) policy_ledger_availability_evidence_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) transaction_append_denial_gate_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyAvailability {
    pub(crate) availability_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) policy_ledger_availability_evidence_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAuditPolicyAvailabilityDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_dry_run_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) source_authority_denial_gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) audit_policy_availability_evidence_verified: bool,
    pub(crate) policy_ledger_dry_run_evidence_verified: bool,
    pub(crate) policy_ledger_availability_evidence_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) transaction_append_denial_gate_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAppendAuthorityAvailability {
    pub(crate) availability_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) audit_policy_availability_evidence_verified: bool,
    pub(crate) policy_ledger_availability_evidence_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAppendAuthorityAvailabilityDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_append_authority_availability_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_dry_run_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_dry_run_hash: [u8; 32],
    pub(crate) source_policy_ledger_availability_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_ledger_aware_acceptance_result_hash: [u8; 32],
    pub(crate) source_ledger_candidate_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) source_authority_denial_gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) append_authority_availability_evidence_verified: bool,
    pub(crate) audit_policy_dry_run_evidence_verified: bool,
    pub(crate) audit_policy_availability_evidence_verified: bool,
    pub(crate) policy_ledger_dry_run_evidence_verified: bool,
    pub(crate) policy_ledger_availability_evidence_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) ledger_evidence_verified: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) transaction_append_denial_gate_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackTransactionAppendAvailabilityDecision {
    pub(crate) decision_hash: [u8; 32],
    pub(crate) source_durable_append_authority_availability_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_append_engine_readiness_decision_hash: [u8; 32],
    pub(crate) source_writer_policy_preflight_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) durable_append_authority_availability_evidence_verified: bool,
    pub(crate) audit_policy_availability_evidence_verified: bool,
    pub(crate) append_engine_ready: bool,
    pub(crate) writer_policy_ready: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackTransactionAppendAuthorityDenialGate {
    pub(crate) gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) source_durable_append_authority_availability_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_append_engine_readiness_decision_hash: [u8; 32],
    pub(crate) source_writer_policy_preflight_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) availability_decision_evidence_verified: bool,
    pub(crate) append_engine_ready: bool,
    pub(crate) writer_policy_ready: bool,
    pub(crate) media_write_policy_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) audit_rollback_target_ids_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) transaction_append_available: bool,
    pub(crate) missing_transaction_append_authority: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackTransactionAppendDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_authority_denial_gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) source_append_record_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) planned_sector_image_hash: [u8; 32],
    pub(crate) readback_sector_image_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) authority_denial_gate_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) append_image_ready: bool,
    pub(crate) blocked_by_authority_denial_gate: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct ScopedRollbackApplyEvidence {
    pub(crate) scope_proof: Option<raios_core::scoped_rollback_apply::ScopedRollbackApplyProof>,
    pub(crate) append_proof:
        Option<raios_core::scoped_rollback_apply::ScopedRollbackAuthorizedAppendProof>,
    pub(crate) verified_apply_proof:
        Option<raios_core::scoped_rollback_apply::ScopedRollbackVerifiedApplyProof>,
    pub(crate) scope_input: raios_core::scoped_rollback_apply::ScopedRollbackApplyInput<'static>,
    pub(crate) scope_decision: raios_core::scoped_rollback_apply::ScopedRollbackApplyDecision,
    pub(crate) scope_decision_hash: [u8; 32],
    pub(crate) append_input: raios_core::scoped_rollback_apply::ScopedRollbackAuthorizedAppendInput,
    pub(crate) append_decision:
        raios_core::scoped_rollback_apply::ScopedRollbackAuthorizedAppendDecision,
    pub(crate) append_hash: [u8; 32],
    pub(crate) apply_decision:
        raios_core::scoped_rollback_apply::ScopedRollbackVerifiedApplyDecision,
}

#[derive(Clone, Copy)]
pub(crate) struct AppliedRollbackRecord {
    pub(crate) event_id: event_log::EventId,
    pub(crate) audit_event_id: event_log::EventId,
    pub(crate) rollback_transaction_hash: [u8; 32],
    pub(crate) write_readback_hash: [u8; 32],
    pub(crate) inspection_hash: [u8; 32],
    pub(crate) audit_record_hash: [u8; 32],
    pub(crate) inspected_rollback_transaction_hash: [u8; 32],
    pub(crate) authorized_append_hash: [u8; 32],
    pub(crate) scope_decision_hash: [u8; 32],
    pub(crate) target_region_write_readback: RollbackTargetRegionWriteReadbackDryRun,
    pub(crate) target_region_sector_inspection: RollbackTargetRegionSectorInspection,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackTargetRegionSectorInspection {
    pub(crate) inspection_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) expected_sector_image_hash: [u8; 32],
    pub(crate) sector_image_hash: [u8; 32],
    pub(crate) audit_record_image_hash: [u8; 32],
    pub(crate) rollback_transaction_image_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) audit_record_offset: u64,
    pub(crate) audit_record_byte_length: u64,
    pub(crate) rollback_transaction_offset: u64,
    pub(crate) rollback_transaction_byte_length: u64,
    pub(crate) padding_offset: u64,
    pub(crate) padding_byte_length: u64,
    pub(crate) label_found: bool,
    pub(crate) read_attempted: bool,
    pub(crate) read_completed: bool,
    pub(crate) sector_hash_verified: bool,
    pub(crate) audit_record_hash_verified: bool,
    pub(crate) rollback_transaction_hash_verified: bool,
    pub(crate) offsets_verified: bool,
    pub(crate) padding_zeroed: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) target_region_write_readback_verified: bool,
    pub(crate) inspection_verified: bool,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryRollbackInspectSourceReference {
    pub(crate) audit_event_id: event_log::EventId,
    pub(crate) event_id: event_log::EventId,
    pub(crate) reference_hash: [u8; 32],
    pub(crate) inspection_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
}

#[derive(Clone, Copy)]
pub(crate) struct RecoveryRollbackInspectSourceReferenceState {
    pub(crate) reference: Option<RecoveryRollbackInspectSourceReference>,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) ram_audit_status: &'static str,
    pub(crate) ram_audit_reason: &'static str,
    pub(crate) source_event_retained: bool,
    pub(crate) audit_event_retained: bool,
    pub(crate) ram_audit_validated: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurablePolicyWriteAuthorityDecision {
    pub(crate) decision_hash: [u8; 32],
    pub(crate) source_durable_append_authority_availability_dry_run_hash: [u8; 32],
    pub(crate) source_transaction_append_dry_run_hash: [u8; 32],
    pub(crate) source_target_region_sector_inspection_hash: [u8; 32],
    pub(crate) source_write_authority_availability_hash: [u8; 32],
    pub(crate) source_audit_policy_availability_hash: [u8; 32],
    pub(crate) source_durable_append_authority_availability_hash: [u8; 32],
    pub(crate) source_authority_denial_gate_hash: [u8; 32],
    pub(crate) source_transaction_append_availability_decision_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) transaction_append_dry_run_verified: bool,
    pub(crate) target_region_sector_inspection_verified: bool,
    pub(crate) write_authority_evidence_verified: bool,
    pub(crate) audit_policy_availability_evidence_verified: bool,
    pub(crate) durable_append_authority_availability_evidence_verified: bool,
    pub(crate) target_span_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) write_authority_available: bool,
    pub(crate) durable_policy_ledger_available: bool,
    pub(crate) durable_audit_policy_available: bool,
    pub(crate) durable_append_authority_available: bool,
    pub(crate) transaction_append_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackTargetRegionWriteReadbackDryRun {
    pub(crate) dry_run_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_policy_preflight_hash: [u8; 32],
    pub(crate) planned_sector_image_hash: [u8; 32],
    pub(crate) readback_sector_image_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) label_found: bool,
    pub(crate) target_range_ready: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) write_attempted: bool,
    pub(crate) write_completed: bool,
    pub(crate) readback_completed: bool,
    pub(crate) readback_matches_planned_image: bool,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableWriterPolicyPreflight {
    pub(crate) preflight_hash: [u8; 32],
    pub(crate) source_append_record_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) target_range_ready: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) durable_audit_writer_available: bool,
    pub(crate) rollback_store_writer_available: bool,
    pub(crate) transaction_append_writer_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAppendTransactionAuthorizationGate {
    pub(crate) gate_hash: [u8; 32],
    pub(crate) source_writer_policy_preflight_hash: [u8; 32],
    pub(crate) source_append_record_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) target_range_ready: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) append_engine_available: bool,
    pub(crate) durable_audit_writer_available: bool,
    pub(crate) rollback_store_writer_available: bool,
    pub(crate) transaction_append_writer_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackAppendEngineReadinessDecision {
    pub(crate) decision_hash: [u8; 32],
    pub(crate) source_authorization_gate_hash: [u8; 32],
    pub(crate) source_writer_policy_preflight_hash: [u8; 32],
    pub(crate) source_append_record_hash: [u8; 32],
    pub(crate) source_sector_plan_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) target_start_lba: u64,
    pub(crate) target_lba_count: u64,
    pub(crate) target_byte_count: u64,
    pub(crate) target_range_ready: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) status: &'static str,
    pub(crate) reason: &'static str,
    pub(crate) append_engine_available: bool,
    pub(crate) durable_audit_writer_available: bool,
    pub(crate) rollback_store_writer_available: bool,
    pub(crate) transaction_append_writer_available: bool,
    pub(crate) ready: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct RollbackDurableAppendAuthorityPreflight {
    pub(crate) preflight_hash: [u8; 32],
    pub(crate) source_write_readback_hash: [u8; 32],
    pub(crate) source_target_region_write_readback_hash: [u8; 32],
    pub(crate) durable_writer_policy_preflight: RollbackDurableWriterPolicyPreflight,
    pub(crate) target_region_discovery: rollback_storage_layout::AuditRollbackTargetRegionDiscovery,
    pub(crate) target_region_media_write_policy_preflight: TargetRegionMediaWritePolicyPreflight,
    pub(crate) scratch_write_readback_verified: bool,
    pub(crate) test_infrastructure_media_write_authority_available: bool,
    pub(crate) remaining_denial_reason: &'static str,
    pub(crate) durable_audit_writer_available: bool,
    pub(crate) rollback_store_writer_available: bool,
    pub(crate) transaction_append_writer_available: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct ServiceSlotActivationRecord {
    pub(crate) schema: &'static str,
    pub(crate) id: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) classification: &'static str,
    pub(crate) persistence: &'static str,
    pub(crate) status: &'static str,
    pub(crate) activation_hash: [u8; 32],
    pub(crate) service_id: &'static str,
    pub(crate) artifact_id: &'static str,
    pub(crate) load_descriptor_id: &'static str,
    pub(crate) descriptor_source_hash: [u8; 32],
    pub(crate) artifact_load_plan_preflight_id: &'static str,
    pub(crate) artifact_load_plan_preflight_hash: [u8; 32],
    pub(crate) artifact_load_plan_preflight_status: &'static str,
    pub(crate) service_slot_intent_id: &'static str,
    pub(crate) ram_only_service_slot_id: &'static str,
    pub(crate) active: bool,
    pub(crate) accepted_preflight: bool,
    pub(crate) authorizes_builtin_current_boot_start: bool,
    pub(crate) authorizes_candidate_artifact_execution: bool,
    pub(crate) writes_persistent_state: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct HelloStateMigrationRecord {
    pub(crate) schema: &'static str,
    pub(crate) id: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) classification: &'static str,
    pub(crate) persistence: &'static str,
    pub(crate) migration_hash: [u8; 32],
    pub(crate) service_id: &'static str,
    pub(crate) ram_only_service_slot_id: &'static str,
    pub(crate) from_version: &'static str,
    pub(crate) to_version: &'static str,
    pub(crate) pre_state_hash: [u8; 32],
    pub(crate) post_state_hash: [u8; 32],
    pub(crate) pre_state_counter: u64,
    pub(crate) post_state_counter: u64,
    pub(crate) state_preserved: bool,
    pub(crate) accepted: bool,
    pub(crate) writes_persistent_state: bool,
    pub(crate) writes_durable_audit_log: bool,
    pub(crate) installs_rollback_plan: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct HelloHotSwapProbationRecord {
    pub(crate) schema: &'static str,
    pub(crate) id: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) classification: &'static str,
    pub(crate) persistence: &'static str,
    pub(crate) status: &'static str,
    pub(crate) probation_hash: [u8; 32],
    pub(crate) service_id: &'static str,
    pub(crate) ram_only_service_slot_id: &'static str,
    pub(crate) previous_version: &'static str,
    pub(crate) new_version: &'static str,
    pub(crate) previous_descriptor_id: &'static str,
    pub(crate) new_descriptor_id: &'static str,
    pub(crate) previous_descriptor_source_hash: [u8; 32],
    pub(crate) new_descriptor_source_hash: [u8; 32],
    pub(crate) previous_artifact_identity_id: &'static str,
    pub(crate) new_artifact_identity_id: &'static str,
    pub(crate) previous_artifact_identity_hash: [u8; 32],
    pub(crate) new_artifact_identity_hash: [u8; 32],
    pub(crate) previous_generation: u64,
    pub(crate) new_generation: u64,
    pub(crate) previous_state_hash: [u8; 32],
    pub(crate) new_state_hash: [u8; 32],
    pub(crate) previous_state_counter: u64,
    pub(crate) new_state_counter: u64,
    pub(crate) state_migration_hash: [u8; 32],
    pub(crate) accepted: bool,
    pub(crate) loads_candidate_bytes: bool,
    pub(crate) maps_executable_pages: bool,
    pub(crate) writes_persistent_state: bool,
    pub(crate) writes_durable_audit_log: bool,
    pub(crate) installs_rollback_plan: bool,
    pub(crate) applies_rollback: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct ArtifactLoadPlanPreflightSelftestCase {
    pub(crate) name: &'static str,
    pub(crate) expected_accept: bool,
    pub(crate) actual_accept: bool,
    pub(crate) passed: bool,
    pub(crate) reason: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) struct LoadRequest {
    pub(crate) source_method: &'static str,
    pub(crate) descriptor: LoadDescriptor,
}
